package ru.DmN.JavaTest.known.big;

import sun.misc.Unsafe;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.AccessibleObject;
import java.lang.reflect.InvocationTargetException;

public class IntUnsafeAccess {
    private static final Object UNSAFE = getUnsafe();
    private static final MethodHandle ALLOCATE;
    private static final MethodHandle GET_LONG;
    private static final MethodHandle PUT_LONG;
    private static final long FIELD_0 = fieldOffset("i0");
    private static final long FIELD_1 = fieldOffset("i1");
    private static final long FIELD_2 = fieldOffset("i2");
    private static final long FIELD_3 = fieldOffset("i3");
    private static final long FIELD_4 = fieldOffset("i4");
    private static final long FIELD_5 = fieldOffset("i5");
    private static final long FIELD_6 = fieldOffset("i6");
    private static final long FIELD_7 = fieldOffset("i7");
    private static final long FIELD_8 = fieldOffset("i8");
    private static final long FIELD_9 = fieldOffset("i9");
    private static final long FIELD_10 = fieldOffset("i10");
    private static final long FIELD_11 = fieldOffset("i11");
    private static final long FIELD_12 = fieldOffset("i12");
    private static final long FIELD_13 = fieldOffset("i13");
    private static final long FIELD_14 = fieldOffset("i14");
    private static final long FIELD_15 = fieldOffset("i15");
    private static final long FIELD_16 = fieldOffset("i16");
    private static final long FIELD_17 = fieldOffset("i17");
    private static final long FIELD_18 = fieldOffset("i18");
    private static final long FIELD_19 = fieldOffset("i19");
    private static final long FIELD_20 = fieldOffset("i20");
    private static final long FIELD_21 = fieldOffset("i21");
    private static final long FIELD_22 = fieldOffset("i22");
    private static final long FIELD_23 = fieldOffset("i23");
    private static final long FIELD_24 = fieldOffset("i24");
    private static final long FIELD_25 = fieldOffset("i25");
    private static final long FIELD_26 = fieldOffset("i26");
    private static final long FIELD_27 = fieldOffset("i27");
    private static final long FIELD_28 = fieldOffset("i28");
    private static final long FIELD_29 = fieldOffset("i29");
    private static final long FIELD_30 = fieldOffset("i30");
    private static final long FIELD_31 = fieldOffset("i31");
    private static final long FIELD_32 = fieldOffset("i32");
    private static final long FIELD_33 = fieldOffset("i33");
    private static final long FIELD_34 = fieldOffset("i34");
    private static final long FIELD_35 = fieldOffset("i35");
    private static final long FIELD_36 = fieldOffset("i36");
    private static final long FIELD_37 = fieldOffset("i37");
    private static final long FIELD_38 = fieldOffset("i38");
    private static final long FIELD_39 = fieldOffset("i39");
    private static final long FIELD_40 = fieldOffset("i40");
    private static final long FIELD_41 = fieldOffset("i41");
    private static final long FIELD_42 = fieldOffset("i42");
    private static final long FIELD_43 = fieldOffset("i43");
    private static final long FIELD_44 = fieldOffset("i44");
    private static final long FIELD_45 = fieldOffset("i45");
    private static final long FIELD_46 = fieldOffset("i46");
    private static final long FIELD_47 = fieldOffset("i47");
    private static final long FIELD_48 = fieldOffset("i48");
    private static final long FIELD_49 = fieldOffset("i49");
    private static final long FIELD_50 = fieldOffset("i50");
    private static final long FIELD_51 = fieldOffset("i51");
    private static final long FIELD_52 = fieldOffset("i52");
    private static final long FIELD_53 = fieldOffset("i53");
    private static final long FIELD_54 = fieldOffset("i54");
    private static final long FIELD_55 = fieldOffset("i55");
    private static final long FIELD_56 = fieldOffset("i56");
    private static final long FIELD_57 = fieldOffset("i57");
    private static final long FIELD_58 = fieldOffset("i58");
    private static final long FIELD_59 = fieldOffset("i59");
    private static final long FIELD_60 = fieldOffset("i60");
    private static final long FIELD_61 = fieldOffset("i61");
    private static final long FIELD_62 = fieldOffset("i62");
    private static final long FIELD_63 = fieldOffset("i63");
    private static final long FIELD_64 = fieldOffset("i64");
    private static final long FIELD_65 = fieldOffset("i65");
    private static final long FIELD_66 = fieldOffset("i66");
    private static final long FIELD_67 = fieldOffset("i67");
    private static final long FIELD_68 = fieldOffset("i68");
    private static final long FIELD_69 = fieldOffset("i69");
    private static final long FIELD_70 = fieldOffset("i70");
    private static final long FIELD_71 = fieldOffset("i71");
    private static final long FIELD_72 = fieldOffset("i72");
    private static final long FIELD_73 = fieldOffset("i73");
    private static final long FIELD_74 = fieldOffset("i74");
    private static final long FIELD_75 = fieldOffset("i75");
    private static final long FIELD_76 = fieldOffset("i76");
    private static final long FIELD_77 = fieldOffset("i77");
    private static final long FIELD_78 = fieldOffset("i78");
    private static final long FIELD_79 = fieldOffset("i79");
    private static final long FIELD_80 = fieldOffset("i80");
    private static final long FIELD_81 = fieldOffset("i81");
    private static final long FIELD_82 = fieldOffset("i82");
    private static final long FIELD_83 = fieldOffset("i83");
    private static final long FIELD_84 = fieldOffset("i84");
    private static final long FIELD_85 = fieldOffset("i85");
    private static final long FIELD_86 = fieldOffset("i86");
    private static final long FIELD_87 = fieldOffset("i87");
    private static final long FIELD_88 = fieldOffset("i88");
    private static final long FIELD_89 = fieldOffset("i89");
    private static final long FIELD_90 = fieldOffset("i90");
    private static final long FIELD_91 = fieldOffset("i91");
    private static final long FIELD_92 = fieldOffset("i92");
    private static final long FIELD_93 = fieldOffset("i93");
    private static final long FIELD_94 = fieldOffset("i94");
    private static final long FIELD_95 = fieldOffset("i95");
    private static final long FIELD_96 = fieldOffset("i96");
    private static final long FIELD_97 = fieldOffset("i97");
    private static final long FIELD_98 = fieldOffset("i98");
    private static final long FIELD_99 = fieldOffset("i99");
    private static final long FIELD_100 = fieldOffset("i100");
    private static final long FIELD_101 = fieldOffset("i101");
    private static final long FIELD_102 = fieldOffset("i102");
    private static final long FIELD_103 = fieldOffset("i103");
    private static final long FIELD_104 = fieldOffset("i104");
    private static final long FIELD_105 = fieldOffset("i105");
    private static final long FIELD_106 = fieldOffset("i106");
    private static final long FIELD_107 = fieldOffset("i107");
    private static final long FIELD_108 = fieldOffset("i108");
    private static final long FIELD_109 = fieldOffset("i109");
    private static final long FIELD_110 = fieldOffset("i110");
    private static final long FIELD_111 = fieldOffset("i111");
    private static final long FIELD_112 = fieldOffset("i112");
    private static final long FIELD_113 = fieldOffset("i113");
    private static final long FIELD_114 = fieldOffset("i114");
    private static final long FIELD_115 = fieldOffset("i115");
    private static final long FIELD_116 = fieldOffset("i116");
    private static final long FIELD_117 = fieldOffset("i117");
    private static final long FIELD_118 = fieldOffset("i118");
    private static final long FIELD_119 = fieldOffset("i119");
    private static final long FIELD_120 = fieldOffset("i120");
    private static final long FIELD_121 = fieldOffset("i121");
    private static final long FIELD_122 = fieldOffset("i122");
    private static final long FIELD_123 = fieldOffset("i123");
    private static final long FIELD_124 = fieldOffset("i124");
    private static final long FIELD_125 = fieldOffset("i125");
    private static final long FIELD_126 = fieldOffset("i126");
    private static final MethodHandle GET_LONG_0;
    private static final MethodHandle GET_LONG_1;
    private static final MethodHandle GET_LONG_2;
    private static final MethodHandle GET_LONG_3;
    private static final MethodHandle GET_LONG_4;
    private static final MethodHandle GET_LONG_5;
    private static final MethodHandle GET_LONG_6;
    private static final MethodHandle GET_LONG_7;
    private static final MethodHandle GET_LONG_8;
    private static final MethodHandle GET_LONG_9;
    private static final MethodHandle GET_LONG_10;
    private static final MethodHandle GET_LONG_11;
    private static final MethodHandle GET_LONG_12;
    private static final MethodHandle GET_LONG_13;
    private static final MethodHandle GET_LONG_14;
    private static final MethodHandle GET_LONG_15;
    private static final MethodHandle GET_LONG_16;
    private static final MethodHandle GET_LONG_17;
    private static final MethodHandle GET_LONG_18;
    private static final MethodHandle GET_LONG_19;
    private static final MethodHandle GET_LONG_20;
    private static final MethodHandle GET_LONG_21;
    private static final MethodHandle GET_LONG_22;
    private static final MethodHandle GET_LONG_23;
    private static final MethodHandle GET_LONG_24;
    private static final MethodHandle GET_LONG_25;
    private static final MethodHandle GET_LONG_26;
    private static final MethodHandle GET_LONG_27;
    private static final MethodHandle GET_LONG_28;
    private static final MethodHandle GET_LONG_29;
    private static final MethodHandle GET_LONG_30;
    private static final MethodHandle GET_LONG_31;
    private static final MethodHandle GET_LONG_32;
    private static final MethodHandle GET_LONG_33;
    private static final MethodHandle GET_LONG_34;
    private static final MethodHandle GET_LONG_35;
    private static final MethodHandle GET_LONG_36;
    private static final MethodHandle GET_LONG_37;
    private static final MethodHandle GET_LONG_38;
    private static final MethodHandle GET_LONG_39;
    private static final MethodHandle GET_LONG_40;
    private static final MethodHandle GET_LONG_41;
    private static final MethodHandle GET_LONG_42;
    private static final MethodHandle GET_LONG_43;
    private static final MethodHandle GET_LONG_44;
    private static final MethodHandle GET_LONG_45;
    private static final MethodHandle GET_LONG_46;
    private static final MethodHandle GET_LONG_47;
    private static final MethodHandle GET_LONG_48;
    private static final MethodHandle GET_LONG_49;
    private static final MethodHandle GET_LONG_50;
    private static final MethodHandle GET_LONG_51;
    private static final MethodHandle GET_LONG_52;
    private static final MethodHandle GET_LONG_53;
    private static final MethodHandle GET_LONG_54;
    private static final MethodHandle GET_LONG_55;
    private static final MethodHandle GET_LONG_56;
    private static final MethodHandle GET_LONG_57;
    private static final MethodHandle GET_LONG_58;
    private static final MethodHandle GET_LONG_59;
    private static final MethodHandle GET_LONG_60;
    private static final MethodHandle GET_LONG_61;
    private static final MethodHandle GET_LONG_62;
    private static final MethodHandle GET_LONG_63;
    private static final MethodHandle GET_LONG_64;
    private static final MethodHandle GET_LONG_65;
    private static final MethodHandle GET_LONG_66;
    private static final MethodHandle GET_LONG_67;
    private static final MethodHandle GET_LONG_68;
    private static final MethodHandle GET_LONG_69;
    private static final MethodHandle GET_LONG_70;
    private static final MethodHandle GET_LONG_71;
    private static final MethodHandle GET_LONG_72;
    private static final MethodHandle GET_LONG_73;
    private static final MethodHandle GET_LONG_74;
    private static final MethodHandle GET_LONG_75;
    private static final MethodHandle GET_LONG_76;
    private static final MethodHandle GET_LONG_77;
    private static final MethodHandle GET_LONG_78;
    private static final MethodHandle GET_LONG_79;
    private static final MethodHandle GET_LONG_80;
    private static final MethodHandle GET_LONG_81;
    private static final MethodHandle GET_LONG_82;
    private static final MethodHandle GET_LONG_83;
    private static final MethodHandle GET_LONG_84;
    private static final MethodHandle GET_LONG_85;
    private static final MethodHandle GET_LONG_86;
    private static final MethodHandle GET_LONG_87;
    private static final MethodHandle GET_LONG_88;
    private static final MethodHandle GET_LONG_89;
    private static final MethodHandle GET_LONG_90;
    private static final MethodHandle GET_LONG_91;
    private static final MethodHandle GET_LONG_92;
    private static final MethodHandle GET_LONG_93;
    private static final MethodHandle GET_LONG_94;
    private static final MethodHandle GET_LONG_95;
    private static final MethodHandle GET_LONG_96;
    private static final MethodHandle GET_LONG_97;
    private static final MethodHandle GET_LONG_98;
    private static final MethodHandle GET_LONG_99;
    private static final MethodHandle GET_LONG_100;
    private static final MethodHandle GET_LONG_101;
    private static final MethodHandle GET_LONG_102;
    private static final MethodHandle GET_LONG_103;
    private static final MethodHandle GET_LONG_104;
    private static final MethodHandle GET_LONG_105;
    private static final MethodHandle GET_LONG_106;
    private static final MethodHandle GET_LONG_107;
    private static final MethodHandle GET_LONG_108;
    private static final MethodHandle GET_LONG_109;
    private static final MethodHandle GET_LONG_110;
    private static final MethodHandle GET_LONG_111;
    private static final MethodHandle GET_LONG_112;
    private static final MethodHandle GET_LONG_113;
    private static final MethodHandle GET_LONG_114;
    private static final MethodHandle GET_LONG_115;
    private static final MethodHandle GET_LONG_116;
    private static final MethodHandle GET_LONG_117;
    private static final MethodHandle GET_LONG_118;
    private static final MethodHandle GET_LONG_119;
    private static final MethodHandle GET_LONG_120;
    private static final MethodHandle GET_LONG_121;
    private static final MethodHandle GET_LONG_122;
    private static final MethodHandle GET_LONG_123;
    private static final MethodHandle GET_LONG_124;
    private static final MethodHandle GET_LONG_125;
    private static final MethodHandle GET_LONG_126;
    private static final MethodHandle PUT_LONG_0;
    private static final MethodHandle PUT_LONG_1;
    private static final MethodHandle PUT_LONG_2;
    private static final MethodHandle PUT_LONG_3;
    private static final MethodHandle PUT_LONG_4;
    private static final MethodHandle PUT_LONG_5;
    private static final MethodHandle PUT_LONG_6;
    private static final MethodHandle PUT_LONG_7;
    private static final MethodHandle PUT_LONG_8;
    private static final MethodHandle PUT_LONG_9;
    private static final MethodHandle PUT_LONG_10;
    private static final MethodHandle PUT_LONG_11;
    private static final MethodHandle PUT_LONG_12;
    private static final MethodHandle PUT_LONG_13;
    private static final MethodHandle PUT_LONG_14;
    private static final MethodHandle PUT_LONG_15;
    private static final MethodHandle PUT_LONG_16;
    private static final MethodHandle PUT_LONG_17;
    private static final MethodHandle PUT_LONG_18;
    private static final MethodHandle PUT_LONG_19;
    private static final MethodHandle PUT_LONG_20;
    private static final MethodHandle PUT_LONG_21;
    private static final MethodHandle PUT_LONG_22;
    private static final MethodHandle PUT_LONG_23;
    private static final MethodHandle PUT_LONG_24;
    private static final MethodHandle PUT_LONG_25;
    private static final MethodHandle PUT_LONG_26;
    private static final MethodHandle PUT_LONG_27;
    private static final MethodHandle PUT_LONG_28;
    private static final MethodHandle PUT_LONG_29;
    private static final MethodHandle PUT_LONG_30;
    private static final MethodHandle PUT_LONG_31;
    private static final MethodHandle PUT_LONG_32;
    private static final MethodHandle PUT_LONG_33;
    private static final MethodHandle PUT_LONG_34;
    private static final MethodHandle PUT_LONG_35;
    private static final MethodHandle PUT_LONG_36;
    private static final MethodHandle PUT_LONG_37;
    private static final MethodHandle PUT_LONG_38;
    private static final MethodHandle PUT_LONG_39;
    private static final MethodHandle PUT_LONG_40;
    private static final MethodHandle PUT_LONG_41;
    private static final MethodHandle PUT_LONG_42;
    private static final MethodHandle PUT_LONG_43;
    private static final MethodHandle PUT_LONG_44;
    private static final MethodHandle PUT_LONG_45;
    private static final MethodHandle PUT_LONG_46;
    private static final MethodHandle PUT_LONG_47;
    private static final MethodHandle PUT_LONG_48;
    private static final MethodHandle PUT_LONG_49;
    private static final MethodHandle PUT_LONG_50;
    private static final MethodHandle PUT_LONG_51;
    private static final MethodHandle PUT_LONG_52;
    private static final MethodHandle PUT_LONG_53;
    private static final MethodHandle PUT_LONG_54;
    private static final MethodHandle PUT_LONG_55;
    private static final MethodHandle PUT_LONG_56;
    private static final MethodHandle PUT_LONG_57;
    private static final MethodHandle PUT_LONG_58;
    private static final MethodHandle PUT_LONG_59;
    private static final MethodHandle PUT_LONG_60;
    private static final MethodHandle PUT_LONG_61;
    private static final MethodHandle PUT_LONG_62;
    private static final MethodHandle PUT_LONG_63;
    private static final MethodHandle PUT_LONG_64;
    private static final MethodHandle PUT_LONG_65;
    private static final MethodHandle PUT_LONG_66;
    private static final MethodHandle PUT_LONG_67;
    private static final MethodHandle PUT_LONG_68;
    private static final MethodHandle PUT_LONG_69;
    private static final MethodHandle PUT_LONG_70;
    private static final MethodHandle PUT_LONG_71;
    private static final MethodHandle PUT_LONG_72;
    private static final MethodHandle PUT_LONG_73;
    private static final MethodHandle PUT_LONG_74;
    private static final MethodHandle PUT_LONG_75;
    private static final MethodHandle PUT_LONG_76;
    private static final MethodHandle PUT_LONG_77;
    private static final MethodHandle PUT_LONG_78;
    private static final MethodHandle PUT_LONG_79;
    private static final MethodHandle PUT_LONG_80;
    private static final MethodHandle PUT_LONG_81;
    private static final MethodHandle PUT_LONG_82;
    private static final MethodHandle PUT_LONG_83;
    private static final MethodHandle PUT_LONG_84;
    private static final MethodHandle PUT_LONG_85;
    private static final MethodHandle PUT_LONG_86;
    private static final MethodHandle PUT_LONG_87;
    private static final MethodHandle PUT_LONG_88;
    private static final MethodHandle PUT_LONG_89;
    private static final MethodHandle PUT_LONG_90;
    private static final MethodHandle PUT_LONG_91;
    private static final MethodHandle PUT_LONG_92;
    private static final MethodHandle PUT_LONG_93;
    private static final MethodHandle PUT_LONG_94;
    private static final MethodHandle PUT_LONG_95;
    private static final MethodHandle PUT_LONG_96;
    private static final MethodHandle PUT_LONG_97;
    private static final MethodHandle PUT_LONG_98;
    private static final MethodHandle PUT_LONG_99;
    private static final MethodHandle PUT_LONG_100;
    private static final MethodHandle PUT_LONG_101;
    private static final MethodHandle PUT_LONG_102;
    private static final MethodHandle PUT_LONG_103;
    private static final MethodHandle PUT_LONG_104;
    private static final MethodHandle PUT_LONG_105;
    private static final MethodHandle PUT_LONG_106;
    private static final MethodHandle PUT_LONG_107;
    private static final MethodHandle PUT_LONG_108;
    private static final MethodHandle PUT_LONG_109;
    private static final MethodHandle PUT_LONG_110;
    private static final MethodHandle PUT_LONG_111;
    private static final MethodHandle PUT_LONG_112;
    private static final MethodHandle PUT_LONG_113;
    private static final MethodHandle PUT_LONG_114;
    private static final MethodHandle PUT_LONG_115;
    private static final MethodHandle PUT_LONG_116;
    private static final MethodHandle PUT_LONG_117;
    private static final MethodHandle PUT_LONG_118;
    private static final MethodHandle PUT_LONG_119;
    private static final MethodHandle PUT_LONG_120;
    private static final MethodHandle PUT_LONG_121;
    private static final MethodHandle PUT_LONG_122;
    private static final MethodHandle PUT_LONG_123;
    private static final MethodHandle PUT_LONG_124;
    private static final MethodHandle PUT_LONG_125;
    private static final MethodHandle PUT_LONG_126;

    public static BigDataClass copy(BigDataClass original) throws Throwable {
        var copy = (BigDataClass) ALLOCATE.invoke(UNSAFE, BigDataClass.class);
        PUT_LONG_0.invoke(copy, (long) GET_LONG_0.invoke(original));
        PUT_LONG_1.invoke(copy, (long) GET_LONG_1.invoke(original));
        PUT_LONG_2.invoke(copy, (long) GET_LONG_2.invoke(original));
        PUT_LONG_3.invoke(copy, (long) GET_LONG_3.invoke(original));
        PUT_LONG_4.invoke(copy, (long) GET_LONG_4.invoke(original));
        PUT_LONG_5.invoke(copy, (long) GET_LONG_5.invoke(original));
        PUT_LONG_6.invoke(copy, (long) GET_LONG_6.invoke(original));
        PUT_LONG_7.invoke(copy, (long) GET_LONG_7.invoke(original));
        PUT_LONG_8.invoke(copy, (long) GET_LONG_8.invoke(original));
        PUT_LONG_9.invoke(copy, (long) GET_LONG_9.invoke(original));
        PUT_LONG_10.invoke(copy, (long) GET_LONG_10.invoke(original));
        PUT_LONG_11.invoke(copy, (long) GET_LONG_11.invoke(original));
        PUT_LONG_12.invoke(copy, (long) GET_LONG_12.invoke(original));
        PUT_LONG_13.invoke(copy, (long) GET_LONG_13.invoke(original));
        PUT_LONG_14.invoke(copy, (long) GET_LONG_14.invoke(original));
        PUT_LONG_15.invoke(copy, (long) GET_LONG_15.invoke(original));
        PUT_LONG_16.invoke(copy, (long) GET_LONG_16.invoke(original));
        PUT_LONG_17.invoke(copy, (long) GET_LONG_17.invoke(original));
        PUT_LONG_18.invoke(copy, (long) GET_LONG_18.invoke(original));
        PUT_LONG_19.invoke(copy, (long) GET_LONG_19.invoke(original));
        PUT_LONG_20.invoke(copy, (long) GET_LONG_20.invoke(original));
        PUT_LONG_21.invoke(copy, (long) GET_LONG_21.invoke(original));
        PUT_LONG_22.invoke(copy, (long) GET_LONG_22.invoke(original));
        PUT_LONG_23.invoke(copy, (long) GET_LONG_23.invoke(original));
        PUT_LONG_24.invoke(copy, (long) GET_LONG_24.invoke(original));
        PUT_LONG_25.invoke(copy, (long) GET_LONG_25.invoke(original));
        PUT_LONG_26.invoke(copy, (long) GET_LONG_26.invoke(original));
        PUT_LONG_27.invoke(copy, (long) GET_LONG_27.invoke(original));
        PUT_LONG_28.invoke(copy, (long) GET_LONG_28.invoke(original));
        PUT_LONG_29.invoke(copy, (long) GET_LONG_29.invoke(original));
        PUT_LONG_30.invoke(copy, (long) GET_LONG_30.invoke(original));
        PUT_LONG_31.invoke(copy, (long) GET_LONG_31.invoke(original));
        PUT_LONG_32.invoke(copy, (long) GET_LONG_32.invoke(original));
        PUT_LONG_33.invoke(copy, (long) GET_LONG_33.invoke(original));
        PUT_LONG_34.invoke(copy, (long) GET_LONG_34.invoke(original));
        PUT_LONG_35.invoke(copy, (long) GET_LONG_35.invoke(original));
        PUT_LONG_36.invoke(copy, (long) GET_LONG_36.invoke(original));
        PUT_LONG_37.invoke(copy, (long) GET_LONG_37.invoke(original));
        PUT_LONG_38.invoke(copy, (long) GET_LONG_38.invoke(original));
        PUT_LONG_39.invoke(copy, (long) GET_LONG_39.invoke(original));
        PUT_LONG_40.invoke(copy, (long) GET_LONG_40.invoke(original));
        PUT_LONG_41.invoke(copy, (long) GET_LONG_41.invoke(original));
        PUT_LONG_42.invoke(copy, (long) GET_LONG_42.invoke(original));
        PUT_LONG_43.invoke(copy, (long) GET_LONG_43.invoke(original));
        PUT_LONG_44.invoke(copy, (long) GET_LONG_44.invoke(original));
        PUT_LONG_45.invoke(copy, (long) GET_LONG_45.invoke(original));
        PUT_LONG_46.invoke(copy, (long) GET_LONG_46.invoke(original));
        PUT_LONG_47.invoke(copy, (long) GET_LONG_47.invoke(original));
        PUT_LONG_48.invoke(copy, (long) GET_LONG_48.invoke(original));
        PUT_LONG_49.invoke(copy, (long) GET_LONG_49.invoke(original));
        PUT_LONG_50.invoke(copy, (long) GET_LONG_50.invoke(original));
        PUT_LONG_51.invoke(copy, (long) GET_LONG_51.invoke(original));
        PUT_LONG_52.invoke(copy, (long) GET_LONG_52.invoke(original));
        PUT_LONG_53.invoke(copy, (long) GET_LONG_53.invoke(original));
        PUT_LONG_54.invoke(copy, (long) GET_LONG_54.invoke(original));
        PUT_LONG_55.invoke(copy, (long) GET_LONG_55.invoke(original));
        PUT_LONG_56.invoke(copy, (long) GET_LONG_56.invoke(original));
        PUT_LONG_57.invoke(copy, (long) GET_LONG_57.invoke(original));
        PUT_LONG_58.invoke(copy, (long) GET_LONG_58.invoke(original));
        PUT_LONG_59.invoke(copy, (long) GET_LONG_59.invoke(original));
        PUT_LONG_60.invoke(copy, (long) GET_LONG_60.invoke(original));
        PUT_LONG_61.invoke(copy, (long) GET_LONG_61.invoke(original));
        PUT_LONG_62.invoke(copy, (long) GET_LONG_62.invoke(original));
        PUT_LONG_63.invoke(copy, (long) GET_LONG_63.invoke(original));
        PUT_LONG_64.invoke(copy, (long) GET_LONG_64.invoke(original));
        PUT_LONG_65.invoke(copy, (long) GET_LONG_65.invoke(original));
        PUT_LONG_66.invoke(copy, (long) GET_LONG_66.invoke(original));
        PUT_LONG_67.invoke(copy, (long) GET_LONG_67.invoke(original));
        PUT_LONG_68.invoke(copy, (long) GET_LONG_68.invoke(original));
        PUT_LONG_69.invoke(copy, (long) GET_LONG_69.invoke(original));
        PUT_LONG_70.invoke(copy, (long) GET_LONG_70.invoke(original));
        PUT_LONG_71.invoke(copy, (long) GET_LONG_71.invoke(original));
        PUT_LONG_72.invoke(copy, (long) GET_LONG_72.invoke(original));
        PUT_LONG_73.invoke(copy, (long) GET_LONG_73.invoke(original));
        PUT_LONG_74.invoke(copy, (long) GET_LONG_74.invoke(original));
        PUT_LONG_75.invoke(copy, (long) GET_LONG_75.invoke(original));
        PUT_LONG_76.invoke(copy, (long) GET_LONG_76.invoke(original));
        PUT_LONG_77.invoke(copy, (long) GET_LONG_77.invoke(original));
        PUT_LONG_78.invoke(copy, (long) GET_LONG_78.invoke(original));
        PUT_LONG_79.invoke(copy, (long) GET_LONG_79.invoke(original));
        PUT_LONG_80.invoke(copy, (long) GET_LONG_80.invoke(original));
        PUT_LONG_81.invoke(copy, (long) GET_LONG_81.invoke(original));
        PUT_LONG_82.invoke(copy, (long) GET_LONG_82.invoke(original));
        PUT_LONG_83.invoke(copy, (long) GET_LONG_83.invoke(original));
        PUT_LONG_84.invoke(copy, (long) GET_LONG_84.invoke(original));
        PUT_LONG_85.invoke(copy, (long) GET_LONG_85.invoke(original));
        PUT_LONG_86.invoke(copy, (long) GET_LONG_86.invoke(original));
        PUT_LONG_87.invoke(copy, (long) GET_LONG_87.invoke(original));
        PUT_LONG_88.invoke(copy, (long) GET_LONG_88.invoke(original));
        PUT_LONG_89.invoke(copy, (long) GET_LONG_89.invoke(original));
        PUT_LONG_90.invoke(copy, (long) GET_LONG_90.invoke(original));
        PUT_LONG_91.invoke(copy, (long) GET_LONG_91.invoke(original));
        PUT_LONG_92.invoke(copy, (long) GET_LONG_92.invoke(original));
        PUT_LONG_93.invoke(copy, (long) GET_LONG_93.invoke(original));
        PUT_LONG_94.invoke(copy, (long) GET_LONG_94.invoke(original));
        PUT_LONG_95.invoke(copy, (long) GET_LONG_95.invoke(original));
        PUT_LONG_96.invoke(copy, (long) GET_LONG_96.invoke(original));
        PUT_LONG_97.invoke(copy, (long) GET_LONG_97.invoke(original));
        PUT_LONG_98.invoke(copy, (long) GET_LONG_98.invoke(original));
        PUT_LONG_99.invoke(copy, (long) GET_LONG_99.invoke(original));
        PUT_LONG_100.invoke(copy, (long) GET_LONG_100.invoke(original));
        PUT_LONG_101.invoke(copy, (long) GET_LONG_101.invoke(original));
        PUT_LONG_102.invoke(copy, (long) GET_LONG_102.invoke(original));
        PUT_LONG_103.invoke(copy, (long) GET_LONG_103.invoke(original));
        PUT_LONG_104.invoke(copy, (long) GET_LONG_104.invoke(original));
        PUT_LONG_105.invoke(copy, (long) GET_LONG_105.invoke(original));
        PUT_LONG_106.invoke(copy, (long) GET_LONG_106.invoke(original));
        PUT_LONG_107.invoke(copy, (long) GET_LONG_107.invoke(original));
        PUT_LONG_108.invoke(copy, (long) GET_LONG_108.invoke(original));
        PUT_LONG_109.invoke(copy, (long) GET_LONG_109.invoke(original));
        PUT_LONG_110.invoke(copy, (long) GET_LONG_110.invoke(original));
        PUT_LONG_111.invoke(copy, (long) GET_LONG_111.invoke(original));
        PUT_LONG_112.invoke(copy, (long) GET_LONG_112.invoke(original));
        PUT_LONG_113.invoke(copy, (long) GET_LONG_113.invoke(original));
        PUT_LONG_114.invoke(copy, (long) GET_LONG_114.invoke(original));
        PUT_LONG_115.invoke(copy, (long) GET_LONG_115.invoke(original));
        PUT_LONG_116.invoke(copy, (long) GET_LONG_116.invoke(original));
        PUT_LONG_117.invoke(copy, (long) GET_LONG_117.invoke(original));
        PUT_LONG_118.invoke(copy, (long) GET_LONG_118.invoke(original));
        PUT_LONG_119.invoke(copy, (long) GET_LONG_119.invoke(original));
        PUT_LONG_120.invoke(copy, (long) GET_LONG_120.invoke(original));
        PUT_LONG_121.invoke(copy, (long) GET_LONG_121.invoke(original));
        PUT_LONG_122.invoke(copy, (long) GET_LONG_122.invoke(original));
        PUT_LONG_123.invoke(copy, (long) GET_LONG_123.invoke(original));
        PUT_LONG_124.invoke(copy, (long) GET_LONG_124.invoke(original));
        PUT_LONG_125.invoke(copy, (long) GET_LONG_125.invoke(original));
        PUT_LONG_126.invoke(copy, (long) GET_LONG_126.invoke(original));
        return copy;
    }

    static {
        try {
            var field = MethodHandles.Lookup.class.getDeclaredField("IMPL_LOOKUP");
            forceAccess(field);
            var lookup = (MethodHandles.Lookup) field.get(null);
            ALLOCATE = lookup.unreflect(Class.forName("jdk.internal.misc.Unsafe").getDeclaredMethod("allocateInstance", Class.class));
            GET_LONG = lookup.unreflect(Class.forName("jdk.internal.misc.Unsafe").getDeclaredMethod("getLong", Object.class, long.class)).bindTo(UNSAFE);
            PUT_LONG = lookup.unreflect(Class.forName("jdk.internal.misc.Unsafe").getDeclaredMethod("putLong", Object.class, long.class, long.class)).bindTo(UNSAFE);

            GET_LONG_0 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_0);
            GET_LONG_1 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_1);
            GET_LONG_2 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_2);
            GET_LONG_3 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_3);
            GET_LONG_4 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_4);
            GET_LONG_5 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_5);
            GET_LONG_6 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_6);
            GET_LONG_7 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_7);
            GET_LONG_8 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_8);
            GET_LONG_9 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_9);
            GET_LONG_10 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_10);
            GET_LONG_11 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_11);
            GET_LONG_12 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_12);
            GET_LONG_13 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_13);
            GET_LONG_14 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_14);
            GET_LONG_15 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_15);
            GET_LONG_16 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_16);
            GET_LONG_17 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_17);
            GET_LONG_18 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_18);
            GET_LONG_19 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_19);
            GET_LONG_20 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_20);
            GET_LONG_21 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_21);
            GET_LONG_22 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_22);
            GET_LONG_23 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_23);
            GET_LONG_24 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_24);
            GET_LONG_25 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_25);
            GET_LONG_26 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_26);
            GET_LONG_27 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_27);
            GET_LONG_28 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_28);
            GET_LONG_29 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_29);
            GET_LONG_30 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_30);
            GET_LONG_31 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_31);
            GET_LONG_32 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_32);
            GET_LONG_33 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_33);
            GET_LONG_34 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_34);
            GET_LONG_35 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_35);
            GET_LONG_36 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_36);
            GET_LONG_37 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_37);
            GET_LONG_38 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_38);
            GET_LONG_39 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_39);
            GET_LONG_40 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_40);
            GET_LONG_41 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_41);
            GET_LONG_42 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_42);
            GET_LONG_43 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_43);
            GET_LONG_44 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_44);
            GET_LONG_45 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_45);
            GET_LONG_46 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_46);
            GET_LONG_47 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_47);
            GET_LONG_48 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_48);
            GET_LONG_49 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_49);
            GET_LONG_50 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_50);
            GET_LONG_51 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_51);
            GET_LONG_52 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_52);
            GET_LONG_53 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_53);
            GET_LONG_54 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_54);
            GET_LONG_55 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_55);
            GET_LONG_56 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_56);
            GET_LONG_57 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_57);
            GET_LONG_58 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_58);
            GET_LONG_59 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_59);
            GET_LONG_60 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_60);
            GET_LONG_61 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_61);
            GET_LONG_62 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_62);
            GET_LONG_63 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_63);
            GET_LONG_64 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_64);
            GET_LONG_65 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_65);
            GET_LONG_66 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_66);
            GET_LONG_67 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_67);
            GET_LONG_68 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_68);
            GET_LONG_69 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_69);
            GET_LONG_70 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_70);
            GET_LONG_71 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_71);
            GET_LONG_72 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_72);
            GET_LONG_73 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_73);
            GET_LONG_74 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_74);
            GET_LONG_75 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_75);
            GET_LONG_76 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_76);
            GET_LONG_77 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_77);
            GET_LONG_78 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_78);
            GET_LONG_79 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_79);
            GET_LONG_80 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_80);
            GET_LONG_81 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_81);
            GET_LONG_82 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_82);
            GET_LONG_83 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_83);
            GET_LONG_84 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_84);
            GET_LONG_85 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_85);
            GET_LONG_86 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_86);
            GET_LONG_87 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_87);
            GET_LONG_88 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_88);
            GET_LONG_89 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_89);
            GET_LONG_90 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_90);
            GET_LONG_91 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_91);
            GET_LONG_92 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_92);
            GET_LONG_93 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_93);
            GET_LONG_94 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_94);
            GET_LONG_95 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_95);
            GET_LONG_96 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_96);
            GET_LONG_97 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_97);
            GET_LONG_98 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_98);
            GET_LONG_99 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_99);
            GET_LONG_100 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_100);
            GET_LONG_101 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_101);
            GET_LONG_102 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_102);
            GET_LONG_103 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_103);
            GET_LONG_104 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_104);
            GET_LONG_105 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_105);
            GET_LONG_106 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_106);
            GET_LONG_107 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_107);
            GET_LONG_108 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_108);
            GET_LONG_109 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_109);
            GET_LONG_110 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_110);
            GET_LONG_111 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_111);
            GET_LONG_112 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_112);
            GET_LONG_113 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_113);
            GET_LONG_114 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_114);
            GET_LONG_115 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_115);
            GET_LONG_116 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_116);
            GET_LONG_117 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_117);
            GET_LONG_118 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_118);
            GET_LONG_119 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_119);
            GET_LONG_120 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_120);
            GET_LONG_121 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_121);
            GET_LONG_122 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_122);
            GET_LONG_123 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_123);
            GET_LONG_124 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_124);
            GET_LONG_125 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_125);
            GET_LONG_126 = MethodHandles.insertArguments(GET_LONG, 1, FIELD_126);
            PUT_LONG_0 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_0);
            PUT_LONG_1 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_1);
            PUT_LONG_2 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_2);
            PUT_LONG_3 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_3);
            PUT_LONG_4 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_4);
            PUT_LONG_5 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_5);
            PUT_LONG_6 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_6);
            PUT_LONG_7 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_7);
            PUT_LONG_8 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_8);
            PUT_LONG_9 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_9);
            PUT_LONG_10 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_10);
            PUT_LONG_11 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_11);
            PUT_LONG_12 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_12);
            PUT_LONG_13 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_13);
            PUT_LONG_14 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_14);
            PUT_LONG_15 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_15);
            PUT_LONG_16 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_16);
            PUT_LONG_17 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_17);
            PUT_LONG_18 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_18);
            PUT_LONG_19 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_19);
            PUT_LONG_20 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_20);
            PUT_LONG_21 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_21);
            PUT_LONG_22 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_22);
            PUT_LONG_23 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_23);
            PUT_LONG_24 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_24);
            PUT_LONG_25 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_25);
            PUT_LONG_26 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_26);
            PUT_LONG_27 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_27);
            PUT_LONG_28 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_28);
            PUT_LONG_29 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_29);
            PUT_LONG_30 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_30);
            PUT_LONG_31 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_31);
            PUT_LONG_32 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_32);
            PUT_LONG_33 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_33);
            PUT_LONG_34 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_34);
            PUT_LONG_35 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_35);
            PUT_LONG_36 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_36);
            PUT_LONG_37 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_37);
            PUT_LONG_38 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_38);
            PUT_LONG_39 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_39);
            PUT_LONG_40 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_40);
            PUT_LONG_41 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_41);
            PUT_LONG_42 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_42);
            PUT_LONG_43 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_43);
            PUT_LONG_44 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_44);
            PUT_LONG_45 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_45);
            PUT_LONG_46 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_46);
            PUT_LONG_47 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_47);
            PUT_LONG_48 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_48);
            PUT_LONG_49 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_49);
            PUT_LONG_50 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_50);
            PUT_LONG_51 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_51);
            PUT_LONG_52 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_52);
            PUT_LONG_53 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_53);
            PUT_LONG_54 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_54);
            PUT_LONG_55 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_55);
            PUT_LONG_56 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_56);
            PUT_LONG_57 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_57);
            PUT_LONG_58 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_58);
            PUT_LONG_59 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_59);
            PUT_LONG_60 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_60);
            PUT_LONG_61 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_61);
            PUT_LONG_62 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_62);
            PUT_LONG_63 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_63);
            PUT_LONG_64 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_64);
            PUT_LONG_65 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_65);
            PUT_LONG_66 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_66);
            PUT_LONG_67 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_67);
            PUT_LONG_68 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_68);
            PUT_LONG_69 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_69);
            PUT_LONG_70 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_70);
            PUT_LONG_71 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_71);
            PUT_LONG_72 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_72);
            PUT_LONG_73 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_73);
            PUT_LONG_74 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_74);
            PUT_LONG_75 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_75);
            PUT_LONG_76 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_76);
            PUT_LONG_77 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_77);
            PUT_LONG_78 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_78);
            PUT_LONG_79 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_79);
            PUT_LONG_80 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_80);
            PUT_LONG_81 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_81);
            PUT_LONG_82 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_82);
            PUT_LONG_83 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_83);
            PUT_LONG_84 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_84);
            PUT_LONG_85 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_85);
            PUT_LONG_86 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_86);
            PUT_LONG_87 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_87);
            PUT_LONG_88 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_88);
            PUT_LONG_89 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_89);
            PUT_LONG_90 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_90);
            PUT_LONG_91 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_91);
            PUT_LONG_92 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_92);
            PUT_LONG_93 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_93);
            PUT_LONG_94 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_94);
            PUT_LONG_95 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_95);
            PUT_LONG_96 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_96);
            PUT_LONG_97 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_97);
            PUT_LONG_98 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_98);
            PUT_LONG_99 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_99);
            PUT_LONG_100 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_100);
            PUT_LONG_101 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_101);
            PUT_LONG_102 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_102);
            PUT_LONG_103 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_103);
            PUT_LONG_104 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_104);
            PUT_LONG_105 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_105);
            PUT_LONG_106 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_106);
            PUT_LONG_107 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_107);
            PUT_LONG_108 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_108);
            PUT_LONG_109 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_109);
            PUT_LONG_110 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_110);
            PUT_LONG_111 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_111);
            PUT_LONG_112 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_112);
            PUT_LONG_113 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_113);
            PUT_LONG_114 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_114);
            PUT_LONG_115 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_115);
            PUT_LONG_116 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_116);
            PUT_LONG_117 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_117);
            PUT_LONG_118 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_118);
            PUT_LONG_119 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_119);
            PUT_LONG_120 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_120);
            PUT_LONG_121 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_121);
            PUT_LONG_122 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_122);
            PUT_LONG_123 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_123);
            PUT_LONG_124 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_124);
            PUT_LONG_125 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_125);
            PUT_LONG_126 = MethodHandles.insertArguments(PUT_LONG, 1, FIELD_126);
        } catch (NoSuchMethodException | IllegalAccessException | ClassNotFoundException | NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
    }

    private static Object getUnsafe() {
        try {
            var field = Class.forName("jdk.internal.misc.Unsafe").getDeclaredField("theUnsafe");
            forceAccess(field);
            return field.get(null);
        } catch (IllegalAccessException | NoSuchFieldException | ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
    }


    private static long fieldOffset(String name) {
        try {
            var offset = Class.forName("jdk.internal.misc.Unsafe").getDeclaredMethod("objectFieldOffset", Class.class, String.class);
            forceAccess(offset);
            return (long) offset.invoke(UNSAFE, BigDataClass.class, name);
        } catch (ClassNotFoundException | NoSuchMethodException | InvocationTargetException |
                 IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

    // Костыль, но пока не знаю как заменить.
    private static void forceAccess(AccessibleObject field) {
        try {
            var unsafe = Unsafe.class.getDeclaredField("theUnsafe");
            unsafe.setAccessible(true);
            ((Unsafe) unsafe.get(null)).putBoolean(field, 12, true);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
}
