package ru.DmN.JavaTest.known.big;

import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.InvocationTargetException;

public class ReflectionAccess {
    private static final Field FIELD_0 = reflectField("i0");
    private static final Field FIELD_1 = reflectField("i1");
    private static final Field FIELD_2 = reflectField("i2");
    private static final Field FIELD_3 = reflectField("i3");
    private static final Field FIELD_4 = reflectField("i4");
    private static final Field FIELD_5 = reflectField("i5");
    private static final Field FIELD_6 = reflectField("i6");
    private static final Field FIELD_7 = reflectField("i7");
    private static final Field FIELD_8 = reflectField("i8");
    private static final Field FIELD_9 = reflectField("i9");
    private static final Field FIELD_10 = reflectField("i10");
    private static final Field FIELD_11 = reflectField("i11");
    private static final Field FIELD_12 = reflectField("i12");
    private static final Field FIELD_13 = reflectField("i13");
    private static final Field FIELD_14 = reflectField("i14");
    private static final Field FIELD_15 = reflectField("i15");
    private static final Field FIELD_16 = reflectField("i16");
    private static final Field FIELD_17 = reflectField("i17");
    private static final Field FIELD_18 = reflectField("i18");
    private static final Field FIELD_19 = reflectField("i19");
    private static final Field FIELD_20 = reflectField("i20");
    private static final Field FIELD_21 = reflectField("i21");
    private static final Field FIELD_22 = reflectField("i22");
    private static final Field FIELD_23 = reflectField("i23");
    private static final Field FIELD_24 = reflectField("i24");
    private static final Field FIELD_25 = reflectField("i25");
    private static final Field FIELD_26 = reflectField("i26");
    private static final Field FIELD_27 = reflectField("i27");
    private static final Field FIELD_28 = reflectField("i28");
    private static final Field FIELD_29 = reflectField("i29");
    private static final Field FIELD_30 = reflectField("i30");
    private static final Field FIELD_31 = reflectField("i31");
    private static final Field FIELD_32 = reflectField("i32");
    private static final Field FIELD_33 = reflectField("i33");
    private static final Field FIELD_34 = reflectField("i34");
    private static final Field FIELD_35 = reflectField("i35");
    private static final Field FIELD_36 = reflectField("i36");
    private static final Field FIELD_37 = reflectField("i37");
    private static final Field FIELD_38 = reflectField("i38");
    private static final Field FIELD_39 = reflectField("i39");
    private static final Field FIELD_40 = reflectField("i40");
    private static final Field FIELD_41 = reflectField("i41");
    private static final Field FIELD_42 = reflectField("i42");
    private static final Field FIELD_43 = reflectField("i43");
    private static final Field FIELD_44 = reflectField("i44");
    private static final Field FIELD_45 = reflectField("i45");
    private static final Field FIELD_46 = reflectField("i46");
    private static final Field FIELD_47 = reflectField("i47");
    private static final Field FIELD_48 = reflectField("i48");
    private static final Field FIELD_49 = reflectField("i49");
    private static final Field FIELD_50 = reflectField("i50");
    private static final Field FIELD_51 = reflectField("i51");
    private static final Field FIELD_52 = reflectField("i52");
    private static final Field FIELD_53 = reflectField("i53");
    private static final Field FIELD_54 = reflectField("i54");
    private static final Field FIELD_55 = reflectField("i55");
    private static final Field FIELD_56 = reflectField("i56");
    private static final Field FIELD_57 = reflectField("i57");
    private static final Field FIELD_58 = reflectField("i58");
    private static final Field FIELD_59 = reflectField("i59");
    private static final Field FIELD_60 = reflectField("i60");
    private static final Field FIELD_61 = reflectField("i61");
    private static final Field FIELD_62 = reflectField("i62");
    private static final Field FIELD_63 = reflectField("i63");
    private static final Field FIELD_64 = reflectField("i64");
    private static final Field FIELD_65 = reflectField("i65");
    private static final Field FIELD_66 = reflectField("i66");
    private static final Field FIELD_67 = reflectField("i67");
    private static final Field FIELD_68 = reflectField("i68");
    private static final Field FIELD_69 = reflectField("i69");
    private static final Field FIELD_70 = reflectField("i70");
    private static final Field FIELD_71 = reflectField("i71");
    private static final Field FIELD_72 = reflectField("i72");
    private static final Field FIELD_73 = reflectField("i73");
    private static final Field FIELD_74 = reflectField("i74");
    private static final Field FIELD_75 = reflectField("i75");
    private static final Field FIELD_76 = reflectField("i76");
    private static final Field FIELD_77 = reflectField("i77");
    private static final Field FIELD_78 = reflectField("i78");
    private static final Field FIELD_79 = reflectField("i79");
    private static final Field FIELD_80 = reflectField("i80");
    private static final Field FIELD_81 = reflectField("i81");
    private static final Field FIELD_82 = reflectField("i82");
    private static final Field FIELD_83 = reflectField("i83");
    private static final Field FIELD_84 = reflectField("i84");
    private static final Field FIELD_85 = reflectField("i85");
    private static final Field FIELD_86 = reflectField("i86");
    private static final Field FIELD_87 = reflectField("i87");
    private static final Field FIELD_88 = reflectField("i88");
    private static final Field FIELD_89 = reflectField("i89");
    private static final Field FIELD_90 = reflectField("i90");
    private static final Field FIELD_91 = reflectField("i91");
    private static final Field FIELD_92 = reflectField("i92");
    private static final Field FIELD_93 = reflectField("i93");
    private static final Field FIELD_94 = reflectField("i94");
    private static final Field FIELD_95 = reflectField("i95");
    private static final Field FIELD_96 = reflectField("i96");
    private static final Field FIELD_97 = reflectField("i97");
    private static final Field FIELD_98 = reflectField("i98");
    private static final Field FIELD_99 = reflectField("i99");
    private static final Field FIELD_100 = reflectField("i100");
    private static final Field FIELD_101 = reflectField("i101");
    private static final Field FIELD_102 = reflectField("i102");
    private static final Field FIELD_103 = reflectField("i103");
    private static final Field FIELD_104 = reflectField("i104");
    private static final Field FIELD_105 = reflectField("i105");
    private static final Field FIELD_106 = reflectField("i106");
    private static final Field FIELD_107 = reflectField("i107");
    private static final Field FIELD_108 = reflectField("i108");
    private static final Field FIELD_109 = reflectField("i109");
    private static final Field FIELD_110 = reflectField("i110");
    private static final Field FIELD_111 = reflectField("i111");
    private static final Field FIELD_112 = reflectField("i112");
    private static final Field FIELD_113 = reflectField("i113");
    private static final Field FIELD_114 = reflectField("i114");
    private static final Field FIELD_115 = reflectField("i115");
    private static final Field FIELD_116 = reflectField("i116");
    private static final Field FIELD_117 = reflectField("i117");
    private static final Field FIELD_118 = reflectField("i118");
    private static final Field FIELD_119 = reflectField("i119");
    private static final Field FIELD_120 = reflectField("i120");
    private static final Field FIELD_121 = reflectField("i121");
    private static final Field FIELD_122 = reflectField("i122");
    private static final Field FIELD_123 = reflectField("i123");
    private static final Field FIELD_124 = reflectField("i124");
    private static final Field FIELD_125 = reflectField("i125");
    private static final Field FIELD_126 = reflectField("i126");
    private static final Constructor<BigDataClass> CONSTRUCTOR;

    public static BigDataClass copy(BigDataClass original) throws InvocationTargetException, InstantiationException, IllegalAccessException {
        var copy = CONSTRUCTOR.newInstance();
        FIELD_0.set(copy, FIELD_0.get(original));
        FIELD_1.set(copy, FIELD_1.get(original));
        FIELD_2.set(copy, FIELD_2.get(original));
        FIELD_3.set(copy, FIELD_3.get(original));
        FIELD_4.set(copy, FIELD_4.get(original));
        FIELD_5.set(copy, FIELD_5.get(original));
        FIELD_6.set(copy, FIELD_6.get(original));
        FIELD_7.set(copy, FIELD_7.get(original));
        FIELD_8.set(copy, FIELD_8.get(original));
        FIELD_9.set(copy, FIELD_9.get(original));
        FIELD_10.set(copy, FIELD_10.get(original));
        FIELD_11.set(copy, FIELD_11.get(original));
        FIELD_12.set(copy, FIELD_12.get(original));
        FIELD_13.set(copy, FIELD_13.get(original));
        FIELD_14.set(copy, FIELD_14.get(original));
        FIELD_15.set(copy, FIELD_15.get(original));
        FIELD_16.set(copy, FIELD_16.get(original));
        FIELD_17.set(copy, FIELD_17.get(original));
        FIELD_18.set(copy, FIELD_18.get(original));
        FIELD_19.set(copy, FIELD_19.get(original));
        FIELD_20.set(copy, FIELD_20.get(original));
        FIELD_21.set(copy, FIELD_21.get(original));
        FIELD_22.set(copy, FIELD_22.get(original));
        FIELD_23.set(copy, FIELD_23.get(original));
        FIELD_24.set(copy, FIELD_24.get(original));
        FIELD_25.set(copy, FIELD_25.get(original));
        FIELD_26.set(copy, FIELD_26.get(original));
        FIELD_27.set(copy, FIELD_27.get(original));
        FIELD_28.set(copy, FIELD_28.get(original));
        FIELD_29.set(copy, FIELD_29.get(original));
        FIELD_30.set(copy, FIELD_30.get(original));
        FIELD_31.set(copy, FIELD_31.get(original));
        FIELD_32.set(copy, FIELD_32.get(original));
        FIELD_33.set(copy, FIELD_33.get(original));
        FIELD_34.set(copy, FIELD_34.get(original));
        FIELD_35.set(copy, FIELD_35.get(original));
        FIELD_36.set(copy, FIELD_36.get(original));
        FIELD_37.set(copy, FIELD_37.get(original));
        FIELD_38.set(copy, FIELD_38.get(original));
        FIELD_39.set(copy, FIELD_39.get(original));
        FIELD_40.set(copy, FIELD_40.get(original));
        FIELD_41.set(copy, FIELD_41.get(original));
        FIELD_42.set(copy, FIELD_42.get(original));
        FIELD_43.set(copy, FIELD_43.get(original));
        FIELD_44.set(copy, FIELD_44.get(original));
        FIELD_45.set(copy, FIELD_45.get(original));
        FIELD_46.set(copy, FIELD_46.get(original));
        FIELD_47.set(copy, FIELD_47.get(original));
        FIELD_48.set(copy, FIELD_48.get(original));
        FIELD_49.set(copy, FIELD_49.get(original));
        FIELD_50.set(copy, FIELD_50.get(original));
        FIELD_51.set(copy, FIELD_51.get(original));
        FIELD_52.set(copy, FIELD_52.get(original));
        FIELD_53.set(copy, FIELD_53.get(original));
        FIELD_54.set(copy, FIELD_54.get(original));
        FIELD_55.set(copy, FIELD_55.get(original));
        FIELD_56.set(copy, FIELD_56.get(original));
        FIELD_57.set(copy, FIELD_57.get(original));
        FIELD_58.set(copy, FIELD_58.get(original));
        FIELD_59.set(copy, FIELD_59.get(original));
        FIELD_60.set(copy, FIELD_60.get(original));
        FIELD_61.set(copy, FIELD_61.get(original));
        FIELD_62.set(copy, FIELD_62.get(original));
        FIELD_63.set(copy, FIELD_63.get(original));
        FIELD_64.set(copy, FIELD_64.get(original));
        FIELD_65.set(copy, FIELD_65.get(original));
        FIELD_66.set(copy, FIELD_66.get(original));
        FIELD_67.set(copy, FIELD_67.get(original));
        FIELD_68.set(copy, FIELD_68.get(original));
        FIELD_69.set(copy, FIELD_69.get(original));
        FIELD_70.set(copy, FIELD_70.get(original));
        FIELD_71.set(copy, FIELD_71.get(original));
        FIELD_72.set(copy, FIELD_72.get(original));
        FIELD_73.set(copy, FIELD_73.get(original));
        FIELD_74.set(copy, FIELD_74.get(original));
        FIELD_75.set(copy, FIELD_75.get(original));
        FIELD_76.set(copy, FIELD_76.get(original));
        FIELD_77.set(copy, FIELD_77.get(original));
        FIELD_78.set(copy, FIELD_78.get(original));
        FIELD_79.set(copy, FIELD_79.get(original));
        FIELD_80.set(copy, FIELD_80.get(original));
        FIELD_81.set(copy, FIELD_81.get(original));
        FIELD_82.set(copy, FIELD_82.get(original));
        FIELD_83.set(copy, FIELD_83.get(original));
        FIELD_84.set(copy, FIELD_84.get(original));
        FIELD_85.set(copy, FIELD_85.get(original));
        FIELD_86.set(copy, FIELD_86.get(original));
        FIELD_87.set(copy, FIELD_87.get(original));
        FIELD_88.set(copy, FIELD_88.get(original));
        FIELD_89.set(copy, FIELD_89.get(original));
        FIELD_90.set(copy, FIELD_90.get(original));
        FIELD_91.set(copy, FIELD_91.get(original));
        FIELD_92.set(copy, FIELD_92.get(original));
        FIELD_93.set(copy, FIELD_93.get(original));
        FIELD_94.set(copy, FIELD_94.get(original));
        FIELD_95.set(copy, FIELD_95.get(original));
        FIELD_96.set(copy, FIELD_96.get(original));
        FIELD_97.set(copy, FIELD_97.get(original));
        FIELD_98.set(copy, FIELD_98.get(original));
        FIELD_99.set(copy, FIELD_99.get(original));
        FIELD_100.set(copy, FIELD_100.get(original));
        FIELD_101.set(copy, FIELD_101.get(original));
        FIELD_102.set(copy, FIELD_102.get(original));
        FIELD_103.set(copy, FIELD_103.get(original));
        FIELD_104.set(copy, FIELD_104.get(original));
        FIELD_105.set(copy, FIELD_105.get(original));
        FIELD_106.set(copy, FIELD_106.get(original));
        FIELD_107.set(copy, FIELD_107.get(original));
        FIELD_108.set(copy, FIELD_108.get(original));
        FIELD_109.set(copy, FIELD_109.get(original));
        FIELD_110.set(copy, FIELD_110.get(original));
        FIELD_111.set(copy, FIELD_111.get(original));
        FIELD_112.set(copy, FIELD_112.get(original));
        FIELD_113.set(copy, FIELD_113.get(original));
        FIELD_114.set(copy, FIELD_114.get(original));
        FIELD_115.set(copy, FIELD_115.get(original));
        FIELD_116.set(copy, FIELD_116.get(original));
        FIELD_117.set(copy, FIELD_117.get(original));
        FIELD_118.set(copy, FIELD_118.get(original));
        FIELD_119.set(copy, FIELD_119.get(original));
        FIELD_120.set(copy, FIELD_120.get(original));
        FIELD_121.set(copy, FIELD_121.get(original));
        FIELD_122.set(copy, FIELD_122.get(original));
        FIELD_123.set(copy, FIELD_123.get(original));
        FIELD_124.set(copy, FIELD_124.get(original));
        FIELD_125.set(copy, FIELD_125.get(original));
        FIELD_126.set(copy, FIELD_126.get(original));
        return copy;
    }

    static {
        try {
            CONSTRUCTOR = BigDataClass.class.getDeclaredConstructor();
            CONSTRUCTOR.setAccessible(true);
        } catch (NoSuchMethodException e) {
            throw new RuntimeException(e);
        }
    }

    private static Field reflectField(String name) {
        try {
            var field = BigDataClass.class.getDeclaredField(name);
            field.setAccessible(true);
            return field;
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
    }
}
