package ru.DmN.JavaTest.known.big;

import sun.misc.Unsafe;

public class SunUnsafeAccess {
    private static final Unsafe UNSAFE = getUnsafe();private static final long FIELD_0 = fieldOffset("i0");
    private static final long FIELD_1 = fieldOffset("i1");
    private static final long FIELD_2 = fieldOffset("i2");
    private static final long FIELD_3 = fieldOffset("i3");
    private static final long FIELD_4 = fieldOffset("i4");
    private static final long FIELD_5 = fieldOffset("i5");
    private static final long FIELD_6 = fieldOffset("i6");
    private static final long FIELD_7 = fieldOffset("i7");
    private static final long FIELD_8 = fieldOffset("i8");
    private static final long FIELD_9 = fieldOffset("i9");
    private static final long FIELD_10 = fieldOffset("i10");
    private static final long FIELD_11 = fieldOffset("i11");
    private static final long FIELD_12 = fieldOffset("i12");
    private static final long FIELD_13 = fieldOffset("i13");
    private static final long FIELD_14 = fieldOffset("i14");
    private static final long FIELD_15 = fieldOffset("i15");
    private static final long FIELD_16 = fieldOffset("i16");
    private static final long FIELD_17 = fieldOffset("i17");
    private static final long FIELD_18 = fieldOffset("i18");
    private static final long FIELD_19 = fieldOffset("i19");
    private static final long FIELD_20 = fieldOffset("i20");
    private static final long FIELD_21 = fieldOffset("i21");
    private static final long FIELD_22 = fieldOffset("i22");
    private static final long FIELD_23 = fieldOffset("i23");
    private static final long FIELD_24 = fieldOffset("i24");
    private static final long FIELD_25 = fieldOffset("i25");
    private static final long FIELD_26 = fieldOffset("i26");
    private static final long FIELD_27 = fieldOffset("i27");
    private static final long FIELD_28 = fieldOffset("i28");
    private static final long FIELD_29 = fieldOffset("i29");
    private static final long FIELD_30 = fieldOffset("i30");
    private static final long FIELD_31 = fieldOffset("i31");
    private static final long FIELD_32 = fieldOffset("i32");
    private static final long FIELD_33 = fieldOffset("i33");
    private static final long FIELD_34 = fieldOffset("i34");
    private static final long FIELD_35 = fieldOffset("i35");
    private static final long FIELD_36 = fieldOffset("i36");
    private static final long FIELD_37 = fieldOffset("i37");
    private static final long FIELD_38 = fieldOffset("i38");
    private static final long FIELD_39 = fieldOffset("i39");
    private static final long FIELD_40 = fieldOffset("i40");
    private static final long FIELD_41 = fieldOffset("i41");
    private static final long FIELD_42 = fieldOffset("i42");
    private static final long FIELD_43 = fieldOffset("i43");
    private static final long FIELD_44 = fieldOffset("i44");
    private static final long FIELD_45 = fieldOffset("i45");
    private static final long FIELD_46 = fieldOffset("i46");
    private static final long FIELD_47 = fieldOffset("i47");
    private static final long FIELD_48 = fieldOffset("i48");
    private static final long FIELD_49 = fieldOffset("i49");
    private static final long FIELD_50 = fieldOffset("i50");
    private static final long FIELD_51 = fieldOffset("i51");
    private static final long FIELD_52 = fieldOffset("i52");
    private static final long FIELD_53 = fieldOffset("i53");
    private static final long FIELD_54 = fieldOffset("i54");
    private static final long FIELD_55 = fieldOffset("i55");
    private static final long FIELD_56 = fieldOffset("i56");
    private static final long FIELD_57 = fieldOffset("i57");
    private static final long FIELD_58 = fieldOffset("i58");
    private static final long FIELD_59 = fieldOffset("i59");
    private static final long FIELD_60 = fieldOffset("i60");
    private static final long FIELD_61 = fieldOffset("i61");
    private static final long FIELD_62 = fieldOffset("i62");
    private static final long FIELD_63 = fieldOffset("i63");
    private static final long FIELD_64 = fieldOffset("i64");
    private static final long FIELD_65 = fieldOffset("i65");
    private static final long FIELD_66 = fieldOffset("i66");
    private static final long FIELD_67 = fieldOffset("i67");
    private static final long FIELD_68 = fieldOffset("i68");
    private static final long FIELD_69 = fieldOffset("i69");
    private static final long FIELD_70 = fieldOffset("i70");
    private static final long FIELD_71 = fieldOffset("i71");
    private static final long FIELD_72 = fieldOffset("i72");
    private static final long FIELD_73 = fieldOffset("i73");
    private static final long FIELD_74 = fieldOffset("i74");
    private static final long FIELD_75 = fieldOffset("i75");
    private static final long FIELD_76 = fieldOffset("i76");
    private static final long FIELD_77 = fieldOffset("i77");
    private static final long FIELD_78 = fieldOffset("i78");
    private static final long FIELD_79 = fieldOffset("i79");
    private static final long FIELD_80 = fieldOffset("i80");
    private static final long FIELD_81 = fieldOffset("i81");
    private static final long FIELD_82 = fieldOffset("i82");
    private static final long FIELD_83 = fieldOffset("i83");
    private static final long FIELD_84 = fieldOffset("i84");
    private static final long FIELD_85 = fieldOffset("i85");
    private static final long FIELD_86 = fieldOffset("i86");
    private static final long FIELD_87 = fieldOffset("i87");
    private static final long FIELD_88 = fieldOffset("i88");
    private static final long FIELD_89 = fieldOffset("i89");
    private static final long FIELD_90 = fieldOffset("i90");
    private static final long FIELD_91 = fieldOffset("i91");
    private static final long FIELD_92 = fieldOffset("i92");
    private static final long FIELD_93 = fieldOffset("i93");
    private static final long FIELD_94 = fieldOffset("i94");
    private static final long FIELD_95 = fieldOffset("i95");
    private static final long FIELD_96 = fieldOffset("i96");
    private static final long FIELD_97 = fieldOffset("i97");
    private static final long FIELD_98 = fieldOffset("i98");
    private static final long FIELD_99 = fieldOffset("i99");
    private static final long FIELD_100 = fieldOffset("i100");
    private static final long FIELD_101 = fieldOffset("i101");
    private static final long FIELD_102 = fieldOffset("i102");
    private static final long FIELD_103 = fieldOffset("i103");
    private static final long FIELD_104 = fieldOffset("i104");
    private static final long FIELD_105 = fieldOffset("i105");
    private static final long FIELD_106 = fieldOffset("i106");
    private static final long FIELD_107 = fieldOffset("i107");
    private static final long FIELD_108 = fieldOffset("i108");
    private static final long FIELD_109 = fieldOffset("i109");
    private static final long FIELD_110 = fieldOffset("i110");
    private static final long FIELD_111 = fieldOffset("i111");
    private static final long FIELD_112 = fieldOffset("i112");
    private static final long FIELD_113 = fieldOffset("i113");
    private static final long FIELD_114 = fieldOffset("i114");
    private static final long FIELD_115 = fieldOffset("i115");
    private static final long FIELD_116 = fieldOffset("i116");
    private static final long FIELD_117 = fieldOffset("i117");
    private static final long FIELD_118 = fieldOffset("i118");
    private static final long FIELD_119 = fieldOffset("i119");
    private static final long FIELD_120 = fieldOffset("i120");
    private static final long FIELD_121 = fieldOffset("i121");
    private static final long FIELD_122 = fieldOffset("i122");
    private static final long FIELD_123 = fieldOffset("i123");
    private static final long FIELD_124 = fieldOffset("i124");
    private static final long FIELD_125 = fieldOffset("i125");
    private static final long FIELD_126 = fieldOffset("i126");

    public static BigDataClass copy(BigDataClass original) throws Throwable {
        var copy = (BigDataClass) UNSAFE.allocateInstance(BigDataClass.class);
        UNSAFE.putLong(copy, FIELD_0, UNSAFE.getLong(original, FIELD_0));
        UNSAFE.putLong(copy, FIELD_1, UNSAFE.getLong(original, FIELD_1));
        UNSAFE.putLong(copy, FIELD_2, UNSAFE.getLong(original, FIELD_2));
        UNSAFE.putLong(copy, FIELD_3, UNSAFE.getLong(original, FIELD_3));
        UNSAFE.putLong(copy, FIELD_4, UNSAFE.getLong(original, FIELD_4));
        UNSAFE.putLong(copy, FIELD_5, UNSAFE.getLong(original, FIELD_5));
        UNSAFE.putLong(copy, FIELD_6, UNSAFE.getLong(original, FIELD_6));
        UNSAFE.putLong(copy, FIELD_7, UNSAFE.getLong(original, FIELD_7));
        UNSAFE.putLong(copy, FIELD_8, UNSAFE.getLong(original, FIELD_8));
        UNSAFE.putLong(copy, FIELD_9, UNSAFE.getLong(original, FIELD_9));
        UNSAFE.putLong(copy, FIELD_10, UNSAFE.getLong(original, FIELD_10));
        UNSAFE.putLong(copy, FIELD_11, UNSAFE.getLong(original, FIELD_11));
        UNSAFE.putLong(copy, FIELD_12, UNSAFE.getLong(original, FIELD_12));
        UNSAFE.putLong(copy, FIELD_13, UNSAFE.getLong(original, FIELD_13));
        UNSAFE.putLong(copy, FIELD_14, UNSAFE.getLong(original, FIELD_14));
        UNSAFE.putLong(copy, FIELD_15, UNSAFE.getLong(original, FIELD_15));
        UNSAFE.putLong(copy, FIELD_16, UNSAFE.getLong(original, FIELD_16));
        UNSAFE.putLong(copy, FIELD_17, UNSAFE.getLong(original, FIELD_17));
        UNSAFE.putLong(copy, FIELD_18, UNSAFE.getLong(original, FIELD_18));
        UNSAFE.putLong(copy, FIELD_19, UNSAFE.getLong(original, FIELD_19));
        UNSAFE.putLong(copy, FIELD_20, UNSAFE.getLong(original, FIELD_20));
        UNSAFE.putLong(copy, FIELD_21, UNSAFE.getLong(original, FIELD_21));
        UNSAFE.putLong(copy, FIELD_22, UNSAFE.getLong(original, FIELD_22));
        UNSAFE.putLong(copy, FIELD_23, UNSAFE.getLong(original, FIELD_23));
        UNSAFE.putLong(copy, FIELD_24, UNSAFE.getLong(original, FIELD_24));
        UNSAFE.putLong(copy, FIELD_25, UNSAFE.getLong(original, FIELD_25));
        UNSAFE.putLong(copy, FIELD_26, UNSAFE.getLong(original, FIELD_26));
        UNSAFE.putLong(copy, FIELD_27, UNSAFE.getLong(original, FIELD_27));
        UNSAFE.putLong(copy, FIELD_28, UNSAFE.getLong(original, FIELD_28));
        UNSAFE.putLong(copy, FIELD_29, UNSAFE.getLong(original, FIELD_29));
        UNSAFE.putLong(copy, FIELD_30, UNSAFE.getLong(original, FIELD_30));
        UNSAFE.putLong(copy, FIELD_31, UNSAFE.getLong(original, FIELD_31));
        UNSAFE.putLong(copy, FIELD_32, UNSAFE.getLong(original, FIELD_32));
        UNSAFE.putLong(copy, FIELD_33, UNSAFE.getLong(original, FIELD_33));
        UNSAFE.putLong(copy, FIELD_34, UNSAFE.getLong(original, FIELD_34));
        UNSAFE.putLong(copy, FIELD_35, UNSAFE.getLong(original, FIELD_35));
        UNSAFE.putLong(copy, FIELD_36, UNSAFE.getLong(original, FIELD_36));
        UNSAFE.putLong(copy, FIELD_37, UNSAFE.getLong(original, FIELD_37));
        UNSAFE.putLong(copy, FIELD_38, UNSAFE.getLong(original, FIELD_38));
        UNSAFE.putLong(copy, FIELD_39, UNSAFE.getLong(original, FIELD_39));
        UNSAFE.putLong(copy, FIELD_40, UNSAFE.getLong(original, FIELD_40));
        UNSAFE.putLong(copy, FIELD_41, UNSAFE.getLong(original, FIELD_41));
        UNSAFE.putLong(copy, FIELD_42, UNSAFE.getLong(original, FIELD_42));
        UNSAFE.putLong(copy, FIELD_43, UNSAFE.getLong(original, FIELD_43));
        UNSAFE.putLong(copy, FIELD_44, UNSAFE.getLong(original, FIELD_44));
        UNSAFE.putLong(copy, FIELD_45, UNSAFE.getLong(original, FIELD_45));
        UNSAFE.putLong(copy, FIELD_46, UNSAFE.getLong(original, FIELD_46));
        UNSAFE.putLong(copy, FIELD_47, UNSAFE.getLong(original, FIELD_47));
        UNSAFE.putLong(copy, FIELD_48, UNSAFE.getLong(original, FIELD_48));
        UNSAFE.putLong(copy, FIELD_49, UNSAFE.getLong(original, FIELD_49));
        UNSAFE.putLong(copy, FIELD_50, UNSAFE.getLong(original, FIELD_50));
        UNSAFE.putLong(copy, FIELD_51, UNSAFE.getLong(original, FIELD_51));
        UNSAFE.putLong(copy, FIELD_52, UNSAFE.getLong(original, FIELD_52));
        UNSAFE.putLong(copy, FIELD_53, UNSAFE.getLong(original, FIELD_53));
        UNSAFE.putLong(copy, FIELD_54, UNSAFE.getLong(original, FIELD_54));
        UNSAFE.putLong(copy, FIELD_55, UNSAFE.getLong(original, FIELD_55));
        UNSAFE.putLong(copy, FIELD_56, UNSAFE.getLong(original, FIELD_56));
        UNSAFE.putLong(copy, FIELD_57, UNSAFE.getLong(original, FIELD_57));
        UNSAFE.putLong(copy, FIELD_58, UNSAFE.getLong(original, FIELD_58));
        UNSAFE.putLong(copy, FIELD_59, UNSAFE.getLong(original, FIELD_59));
        UNSAFE.putLong(copy, FIELD_60, UNSAFE.getLong(original, FIELD_60));
        UNSAFE.putLong(copy, FIELD_61, UNSAFE.getLong(original, FIELD_61));
        UNSAFE.putLong(copy, FIELD_62, UNSAFE.getLong(original, FIELD_62));
        UNSAFE.putLong(copy, FIELD_63, UNSAFE.getLong(original, FIELD_63));
        UNSAFE.putLong(copy, FIELD_64, UNSAFE.getLong(original, FIELD_64));
        UNSAFE.putLong(copy, FIELD_65, UNSAFE.getLong(original, FIELD_65));
        UNSAFE.putLong(copy, FIELD_66, UNSAFE.getLong(original, FIELD_66));
        UNSAFE.putLong(copy, FIELD_67, UNSAFE.getLong(original, FIELD_67));
        UNSAFE.putLong(copy, FIELD_68, UNSAFE.getLong(original, FIELD_68));
        UNSAFE.putLong(copy, FIELD_69, UNSAFE.getLong(original, FIELD_69));
        UNSAFE.putLong(copy, FIELD_70, UNSAFE.getLong(original, FIELD_70));
        UNSAFE.putLong(copy, FIELD_71, UNSAFE.getLong(original, FIELD_71));
        UNSAFE.putLong(copy, FIELD_72, UNSAFE.getLong(original, FIELD_72));
        UNSAFE.putLong(copy, FIELD_73, UNSAFE.getLong(original, FIELD_73));
        UNSAFE.putLong(copy, FIELD_74, UNSAFE.getLong(original, FIELD_74));
        UNSAFE.putLong(copy, FIELD_75, UNSAFE.getLong(original, FIELD_75));
        UNSAFE.putLong(copy, FIELD_76, UNSAFE.getLong(original, FIELD_76));
        UNSAFE.putLong(copy, FIELD_77, UNSAFE.getLong(original, FIELD_77));
        UNSAFE.putLong(copy, FIELD_78, UNSAFE.getLong(original, FIELD_78));
        UNSAFE.putLong(copy, FIELD_79, UNSAFE.getLong(original, FIELD_79));
        UNSAFE.putLong(copy, FIELD_80, UNSAFE.getLong(original, FIELD_80));
        UNSAFE.putLong(copy, FIELD_81, UNSAFE.getLong(original, FIELD_81));
        UNSAFE.putLong(copy, FIELD_82, UNSAFE.getLong(original, FIELD_82));
        UNSAFE.putLong(copy, FIELD_83, UNSAFE.getLong(original, FIELD_83));
        UNSAFE.putLong(copy, FIELD_84, UNSAFE.getLong(original, FIELD_84));
        UNSAFE.putLong(copy, FIELD_85, UNSAFE.getLong(original, FIELD_85));
        UNSAFE.putLong(copy, FIELD_86, UNSAFE.getLong(original, FIELD_86));
        UNSAFE.putLong(copy, FIELD_87, UNSAFE.getLong(original, FIELD_87));
        UNSAFE.putLong(copy, FIELD_88, UNSAFE.getLong(original, FIELD_88));
        UNSAFE.putLong(copy, FIELD_89, UNSAFE.getLong(original, FIELD_89));
        UNSAFE.putLong(copy, FIELD_90, UNSAFE.getLong(original, FIELD_90));
        UNSAFE.putLong(copy, FIELD_91, UNSAFE.getLong(original, FIELD_91));
        UNSAFE.putLong(copy, FIELD_92, UNSAFE.getLong(original, FIELD_92));
        UNSAFE.putLong(copy, FIELD_93, UNSAFE.getLong(original, FIELD_93));
        UNSAFE.putLong(copy, FIELD_94, UNSAFE.getLong(original, FIELD_94));
        UNSAFE.putLong(copy, FIELD_95, UNSAFE.getLong(original, FIELD_95));
        UNSAFE.putLong(copy, FIELD_96, UNSAFE.getLong(original, FIELD_96));
        UNSAFE.putLong(copy, FIELD_97, UNSAFE.getLong(original, FIELD_97));
        UNSAFE.putLong(copy, FIELD_98, UNSAFE.getLong(original, FIELD_98));
        UNSAFE.putLong(copy, FIELD_99, UNSAFE.getLong(original, FIELD_99));
        UNSAFE.putLong(copy, FIELD_100, UNSAFE.getLong(original, FIELD_100));
        UNSAFE.putLong(copy, FIELD_101, UNSAFE.getLong(original, FIELD_101));
        UNSAFE.putLong(copy, FIELD_102, UNSAFE.getLong(original, FIELD_102));
        UNSAFE.putLong(copy, FIELD_103, UNSAFE.getLong(original, FIELD_103));
        UNSAFE.putLong(copy, FIELD_104, UNSAFE.getLong(original, FIELD_104));
        UNSAFE.putLong(copy, FIELD_105, UNSAFE.getLong(original, FIELD_105));
        UNSAFE.putLong(copy, FIELD_106, UNSAFE.getLong(original, FIELD_106));
        UNSAFE.putLong(copy, FIELD_107, UNSAFE.getLong(original, FIELD_107));
        UNSAFE.putLong(copy, FIELD_108, UNSAFE.getLong(original, FIELD_108));
        UNSAFE.putLong(copy, FIELD_109, UNSAFE.getLong(original, FIELD_109));
        UNSAFE.putLong(copy, FIELD_110, UNSAFE.getLong(original, FIELD_110));
        UNSAFE.putLong(copy, FIELD_111, UNSAFE.getLong(original, FIELD_111));
        UNSAFE.putLong(copy, FIELD_112, UNSAFE.getLong(original, FIELD_112));
        UNSAFE.putLong(copy, FIELD_113, UNSAFE.getLong(original, FIELD_113));
        UNSAFE.putLong(copy, FIELD_114, UNSAFE.getLong(original, FIELD_114));
        UNSAFE.putLong(copy, FIELD_115, UNSAFE.getLong(original, FIELD_115));
        UNSAFE.putLong(copy, FIELD_116, UNSAFE.getLong(original, FIELD_116));
        UNSAFE.putLong(copy, FIELD_117, UNSAFE.getLong(original, FIELD_117));
        UNSAFE.putLong(copy, FIELD_118, UNSAFE.getLong(original, FIELD_118));
        UNSAFE.putLong(copy, FIELD_119, UNSAFE.getLong(original, FIELD_119));
        UNSAFE.putLong(copy, FIELD_120, UNSAFE.getLong(original, FIELD_120));
        UNSAFE.putLong(copy, FIELD_121, UNSAFE.getLong(original, FIELD_121));
        UNSAFE.putLong(copy, FIELD_122, UNSAFE.getLong(original, FIELD_122));
        UNSAFE.putLong(copy, FIELD_123, UNSAFE.getLong(original, FIELD_123));
        UNSAFE.putLong(copy, FIELD_124, UNSAFE.getLong(original, FIELD_124));
        UNSAFE.putLong(copy, FIELD_125, UNSAFE.getLong(original, FIELD_125));
        UNSAFE.putLong(copy, FIELD_126, UNSAFE.getLong(original, FIELD_126));
        return copy;
    }

    private static Unsafe getUnsafe() {
        try {
            var unsafe = Unsafe.class.getDeclaredField("theUnsafe");
            unsafe.setAccessible(true);
            return (Unsafe) unsafe.get(null);
        } catch (IllegalAccessException | NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
    }

    private static long fieldOffset(String name) {
        try {
            var field = BigDataClass.class.getDeclaredField(name);
            field.setAccessible(true);
            return UNSAFE.objectFieldOffset(field);
        } catch (NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
    }
}
