package ru.DmN.JavaTest.known.big;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.invoke.MethodType;
import java.lang.invoke.VarHandle;

public class VarHandleAccess {
    private static final VarHandle FIELD_0;
    private static final VarHandle FIELD_1;
    private static final VarHandle FIELD_2;
    private static final VarHandle FIELD_3;
    private static final VarHandle FIELD_4;
    private static final VarHandle FIELD_5;
    private static final VarHandle FIELD_6;
    private static final VarHandle FIELD_7;
    private static final VarHandle FIELD_8;
    private static final VarHandle FIELD_9;
    private static final VarHandle FIELD_10;
    private static final VarHandle FIELD_11;
    private static final VarHandle FIELD_12;
    private static final VarHandle FIELD_13;
    private static final VarHandle FIELD_14;
    private static final VarHandle FIELD_15;
    private static final VarHandle FIELD_16;
    private static final VarHandle FIELD_17;
    private static final VarHandle FIELD_18;
    private static final VarHandle FIELD_19;
    private static final VarHandle FIELD_20;
    private static final VarHandle FIELD_21;
    private static final VarHandle FIELD_22;
    private static final VarHandle FIELD_23;
    private static final VarHandle FIELD_24;
    private static final VarHandle FIELD_25;
    private static final VarHandle FIELD_26;
    private static final VarHandle FIELD_27;
    private static final VarHandle FIELD_28;
    private static final VarHandle FIELD_29;
    private static final VarHandle FIELD_30;
    private static final VarHandle FIELD_31;
    private static final VarHandle FIELD_32;
    private static final VarHandle FIELD_33;
    private static final VarHandle FIELD_34;
    private static final VarHandle FIELD_35;
    private static final VarHandle FIELD_36;
    private static final VarHandle FIELD_37;
    private static final VarHandle FIELD_38;
    private static final VarHandle FIELD_39;
    private static final VarHandle FIELD_40;
    private static final VarHandle FIELD_41;
    private static final VarHandle FIELD_42;
    private static final VarHandle FIELD_43;
    private static final VarHandle FIELD_44;
    private static final VarHandle FIELD_45;
    private static final VarHandle FIELD_46;
    private static final VarHandle FIELD_47;
    private static final VarHandle FIELD_48;
    private static final VarHandle FIELD_49;
    private static final VarHandle FIELD_50;
    private static final VarHandle FIELD_51;
    private static final VarHandle FIELD_52;
    private static final VarHandle FIELD_53;
    private static final VarHandle FIELD_54;
    private static final VarHandle FIELD_55;
    private static final VarHandle FIELD_56;
    private static final VarHandle FIELD_57;
    private static final VarHandle FIELD_58;
    private static final VarHandle FIELD_59;
    private static final VarHandle FIELD_60;
    private static final VarHandle FIELD_61;
    private static final VarHandle FIELD_62;
    private static final VarHandle FIELD_63;
    private static final VarHandle FIELD_64;
    private static final VarHandle FIELD_65;
    private static final VarHandle FIELD_66;
    private static final VarHandle FIELD_67;
    private static final VarHandle FIELD_68;
    private static final VarHandle FIELD_69;
    private static final VarHandle FIELD_70;
    private static final VarHandle FIELD_71;
    private static final VarHandle FIELD_72;
    private static final VarHandle FIELD_73;
    private static final VarHandle FIELD_74;
    private static final VarHandle FIELD_75;
    private static final VarHandle FIELD_76;
    private static final VarHandle FIELD_77;
    private static final VarHandle FIELD_78;
    private static final VarHandle FIELD_79;
    private static final VarHandle FIELD_80;
    private static final VarHandle FIELD_81;
    private static final VarHandle FIELD_82;
    private static final VarHandle FIELD_83;
    private static final VarHandle FIELD_84;
    private static final VarHandle FIELD_85;
    private static final VarHandle FIELD_86;
    private static final VarHandle FIELD_87;
    private static final VarHandle FIELD_88;
    private static final VarHandle FIELD_89;
    private static final VarHandle FIELD_90;
    private static final VarHandle FIELD_91;
    private static final VarHandle FIELD_92;
    private static final VarHandle FIELD_93;
    private static final VarHandle FIELD_94;
    private static final VarHandle FIELD_95;
    private static final VarHandle FIELD_96;
    private static final VarHandle FIELD_97;
    private static final VarHandle FIELD_98;
    private static final VarHandle FIELD_99;
    private static final VarHandle FIELD_100;
    private static final VarHandle FIELD_101;
    private static final VarHandle FIELD_102;
    private static final VarHandle FIELD_103;
    private static final VarHandle FIELD_104;
    private static final VarHandle FIELD_105;
    private static final VarHandle FIELD_106;
    private static final VarHandle FIELD_107;
    private static final VarHandle FIELD_108;
    private static final VarHandle FIELD_109;
    private static final VarHandle FIELD_110;
    private static final VarHandle FIELD_111;
    private static final VarHandle FIELD_112;
    private static final VarHandle FIELD_113;
    private static final VarHandle FIELD_114;
    private static final VarHandle FIELD_115;
    private static final VarHandle FIELD_116;
    private static final VarHandle FIELD_117;
    private static final VarHandle FIELD_118;
    private static final VarHandle FIELD_119;
    private static final VarHandle FIELD_120;
    private static final VarHandle FIELD_121;
    private static final VarHandle FIELD_122;
    private static final VarHandle FIELD_123;
    private static final VarHandle FIELD_124;
    private static final VarHandle FIELD_125;
    private static final VarHandle FIELD_126;
    private static final MethodHandle CONSTRUCTOR;

    public static BigDataClass copy(BigDataClass original) throws Throwable {
        var copy = (BigDataClass) CONSTRUCTOR.invoke();
        FIELD_0.set(copy, (long) FIELD_0.get(original));
        FIELD_1.set(copy, (long) FIELD_1.get(original));
        FIELD_2.set(copy, (long) FIELD_2.get(original));
        FIELD_3.set(copy, (long) FIELD_3.get(original));
        FIELD_4.set(copy, (long) FIELD_4.get(original));
        FIELD_5.set(copy, (long) FIELD_5.get(original));
        FIELD_6.set(copy, (long) FIELD_6.get(original));
        FIELD_7.set(copy, (long) FIELD_7.get(original));
        FIELD_8.set(copy, (long) FIELD_8.get(original));
        FIELD_9.set(copy, (long) FIELD_9.get(original));
        FIELD_10.set(copy, (long) FIELD_10.get(original));
        FIELD_11.set(copy, (long) FIELD_11.get(original));
        FIELD_12.set(copy, (long) FIELD_12.get(original));
        FIELD_13.set(copy, (long) FIELD_13.get(original));
        FIELD_14.set(copy, (long) FIELD_14.get(original));
        FIELD_15.set(copy, (long) FIELD_15.get(original));
        FIELD_16.set(copy, (long) FIELD_16.get(original));
        FIELD_17.set(copy, (long) FIELD_17.get(original));
        FIELD_18.set(copy, (long) FIELD_18.get(original));
        FIELD_19.set(copy, (long) FIELD_19.get(original));
        FIELD_20.set(copy, (long) FIELD_20.get(original));
        FIELD_21.set(copy, (long) FIELD_21.get(original));
        FIELD_22.set(copy, (long) FIELD_22.get(original));
        FIELD_23.set(copy, (long) FIELD_23.get(original));
        FIELD_24.set(copy, (long) FIELD_24.get(original));
        FIELD_25.set(copy, (long) FIELD_25.get(original));
        FIELD_26.set(copy, (long) FIELD_26.get(original));
        FIELD_27.set(copy, (long) FIELD_27.get(original));
        FIELD_28.set(copy, (long) FIELD_28.get(original));
        FIELD_29.set(copy, (long) FIELD_29.get(original));
        FIELD_30.set(copy, (long) FIELD_30.get(original));
        FIELD_31.set(copy, (long) FIELD_31.get(original));
        FIELD_32.set(copy, (long) FIELD_32.get(original));
        FIELD_33.set(copy, (long) FIELD_33.get(original));
        FIELD_34.set(copy, (long) FIELD_34.get(original));
        FIELD_35.set(copy, (long) FIELD_35.get(original));
        FIELD_36.set(copy, (long) FIELD_36.get(original));
        FIELD_37.set(copy, (long) FIELD_37.get(original));
        FIELD_38.set(copy, (long) FIELD_38.get(original));
        FIELD_39.set(copy, (long) FIELD_39.get(original));
        FIELD_40.set(copy, (long) FIELD_40.get(original));
        FIELD_41.set(copy, (long) FIELD_41.get(original));
        FIELD_42.set(copy, (long) FIELD_42.get(original));
        FIELD_43.set(copy, (long) FIELD_43.get(original));
        FIELD_44.set(copy, (long) FIELD_44.get(original));
        FIELD_45.set(copy, (long) FIELD_45.get(original));
        FIELD_46.set(copy, (long) FIELD_46.get(original));
        FIELD_47.set(copy, (long) FIELD_47.get(original));
        FIELD_48.set(copy, (long) FIELD_48.get(original));
        FIELD_49.set(copy, (long) FIELD_49.get(original));
        FIELD_50.set(copy, (long) FIELD_50.get(original));
        FIELD_51.set(copy, (long) FIELD_51.get(original));
        FIELD_52.set(copy, (long) FIELD_52.get(original));
        FIELD_53.set(copy, (long) FIELD_53.get(original));
        FIELD_54.set(copy, (long) FIELD_54.get(original));
        FIELD_55.set(copy, (long) FIELD_55.get(original));
        FIELD_56.set(copy, (long) FIELD_56.get(original));
        FIELD_57.set(copy, (long) FIELD_57.get(original));
        FIELD_58.set(copy, (long) FIELD_58.get(original));
        FIELD_59.set(copy, (long) FIELD_59.get(original));
        FIELD_60.set(copy, (long) FIELD_60.get(original));
        FIELD_61.set(copy, (long) FIELD_61.get(original));
        FIELD_62.set(copy, (long) FIELD_62.get(original));
        FIELD_63.set(copy, (long) FIELD_63.get(original));
        FIELD_64.set(copy, (long) FIELD_64.get(original));
        FIELD_65.set(copy, (long) FIELD_65.get(original));
        FIELD_66.set(copy, (long) FIELD_66.get(original));
        FIELD_67.set(copy, (long) FIELD_67.get(original));
        FIELD_68.set(copy, (long) FIELD_68.get(original));
        FIELD_69.set(copy, (long) FIELD_69.get(original));
        FIELD_70.set(copy, (long) FIELD_70.get(original));
        FIELD_71.set(copy, (long) FIELD_71.get(original));
        FIELD_72.set(copy, (long) FIELD_72.get(original));
        FIELD_73.set(copy, (long) FIELD_73.get(original));
        FIELD_74.set(copy, (long) FIELD_74.get(original));
        FIELD_75.set(copy, (long) FIELD_75.get(original));
        FIELD_76.set(copy, (long) FIELD_76.get(original));
        FIELD_77.set(copy, (long) FIELD_77.get(original));
        FIELD_78.set(copy, (long) FIELD_78.get(original));
        FIELD_79.set(copy, (long) FIELD_79.get(original));
        FIELD_80.set(copy, (long) FIELD_80.get(original));
        FIELD_81.set(copy, (long) FIELD_81.get(original));
        FIELD_82.set(copy, (long) FIELD_82.get(original));
        FIELD_83.set(copy, (long) FIELD_83.get(original));
        FIELD_84.set(copy, (long) FIELD_84.get(original));
        FIELD_85.set(copy, (long) FIELD_85.get(original));
        FIELD_86.set(copy, (long) FIELD_86.get(original));
        FIELD_87.set(copy, (long) FIELD_87.get(original));
        FIELD_88.set(copy, (long) FIELD_88.get(original));
        FIELD_89.set(copy, (long) FIELD_89.get(original));
        FIELD_90.set(copy, (long) FIELD_90.get(original));
        FIELD_91.set(copy, (long) FIELD_91.get(original));
        FIELD_92.set(copy, (long) FIELD_92.get(original));
        FIELD_93.set(copy, (long) FIELD_93.get(original));
        FIELD_94.set(copy, (long) FIELD_94.get(original));
        FIELD_95.set(copy, (long) FIELD_95.get(original));
        FIELD_96.set(copy, (long) FIELD_96.get(original));
        FIELD_97.set(copy, (long) FIELD_97.get(original));
        FIELD_98.set(copy, (long) FIELD_98.get(original));
        FIELD_99.set(copy, (long) FIELD_99.get(original));
        FIELD_100.set(copy, (long) FIELD_100.get(original));
        FIELD_101.set(copy, (long) FIELD_101.get(original));
        FIELD_102.set(copy, (long) FIELD_102.get(original));
        FIELD_103.set(copy, (long) FIELD_103.get(original));
        FIELD_104.set(copy, (long) FIELD_104.get(original));
        FIELD_105.set(copy, (long) FIELD_105.get(original));
        FIELD_106.set(copy, (long) FIELD_106.get(original));
        FIELD_107.set(copy, (long) FIELD_107.get(original));
        FIELD_108.set(copy, (long) FIELD_108.get(original));
        FIELD_109.set(copy, (long) FIELD_109.get(original));
        FIELD_110.set(copy, (long) FIELD_110.get(original));
        FIELD_111.set(copy, (long) FIELD_111.get(original));
        FIELD_112.set(copy, (long) FIELD_112.get(original));
        FIELD_113.set(copy, (long) FIELD_113.get(original));
        FIELD_114.set(copy, (long) FIELD_114.get(original));
        FIELD_115.set(copy, (long) FIELD_115.get(original));
        FIELD_116.set(copy, (long) FIELD_116.get(original));
        FIELD_117.set(copy, (long) FIELD_117.get(original));
        FIELD_118.set(copy, (long) FIELD_118.get(original));
        FIELD_119.set(copy, (long) FIELD_119.get(original));
        FIELD_120.set(copy, (long) FIELD_120.get(original));
        FIELD_121.set(copy, (long) FIELD_121.get(original));
        FIELD_122.set(copy, (long) FIELD_122.get(original));
        FIELD_123.set(copy, (long) FIELD_123.get(original));
        FIELD_124.set(copy, (long) FIELD_124.get(original));
        FIELD_125.set(copy, (long) FIELD_125.get(original));
        FIELD_126.set(copy, (long) FIELD_126.get(original));
        return copy;
    }

    static {
        try {
            var lookup = MethodHandles.lookup();
            FIELD_0 = lookup.findVarHandle(BigDataClass.class, "i0", long.class);
            FIELD_1 = lookup.findVarHandle(BigDataClass.class, "i1", long.class);
            FIELD_2 = lookup.findVarHandle(BigDataClass.class, "i2", long.class);
            FIELD_3 = lookup.findVarHandle(BigDataClass.class, "i3", long.class);
            FIELD_4 = lookup.findVarHandle(BigDataClass.class, "i4", long.class);
            FIELD_5 = lookup.findVarHandle(BigDataClass.class, "i5", long.class);
            FIELD_6 = lookup.findVarHandle(BigDataClass.class, "i6", long.class);
            FIELD_7 = lookup.findVarHandle(BigDataClass.class, "i7", long.class);
            FIELD_8 = lookup.findVarHandle(BigDataClass.class, "i8", long.class);
            FIELD_9 = lookup.findVarHandle(BigDataClass.class, "i9", long.class);
            FIELD_10 = lookup.findVarHandle(BigDataClass.class, "i10", long.class);
            FIELD_11 = lookup.findVarHandle(BigDataClass.class, "i11", long.class);
            FIELD_12 = lookup.findVarHandle(BigDataClass.class, "i12", long.class);
            FIELD_13 = lookup.findVarHandle(BigDataClass.class, "i13", long.class);
            FIELD_14 = lookup.findVarHandle(BigDataClass.class, "i14", long.class);
            FIELD_15 = lookup.findVarHandle(BigDataClass.class, "i15", long.class);
            FIELD_16 = lookup.findVarHandle(BigDataClass.class, "i16", long.class);
            FIELD_17 = lookup.findVarHandle(BigDataClass.class, "i17", long.class);
            FIELD_18 = lookup.findVarHandle(BigDataClass.class, "i18", long.class);
            FIELD_19 = lookup.findVarHandle(BigDataClass.class, "i19", long.class);
            FIELD_20 = lookup.findVarHandle(BigDataClass.class, "i20", long.class);
            FIELD_21 = lookup.findVarHandle(BigDataClass.class, "i21", long.class);
            FIELD_22 = lookup.findVarHandle(BigDataClass.class, "i22", long.class);
            FIELD_23 = lookup.findVarHandle(BigDataClass.class, "i23", long.class);
            FIELD_24 = lookup.findVarHandle(BigDataClass.class, "i24", long.class);
            FIELD_25 = lookup.findVarHandle(BigDataClass.class, "i25", long.class);
            FIELD_26 = lookup.findVarHandle(BigDataClass.class, "i26", long.class);
            FIELD_27 = lookup.findVarHandle(BigDataClass.class, "i27", long.class);
            FIELD_28 = lookup.findVarHandle(BigDataClass.class, "i28", long.class);
            FIELD_29 = lookup.findVarHandle(BigDataClass.class, "i29", long.class);
            FIELD_30 = lookup.findVarHandle(BigDataClass.class, "i30", long.class);
            FIELD_31 = lookup.findVarHandle(BigDataClass.class, "i31", long.class);
            FIELD_32 = lookup.findVarHandle(BigDataClass.class, "i32", long.class);
            FIELD_33 = lookup.findVarHandle(BigDataClass.class, "i33", long.class);
            FIELD_34 = lookup.findVarHandle(BigDataClass.class, "i34", long.class);
            FIELD_35 = lookup.findVarHandle(BigDataClass.class, "i35", long.class);
            FIELD_36 = lookup.findVarHandle(BigDataClass.class, "i36", long.class);
            FIELD_37 = lookup.findVarHandle(BigDataClass.class, "i37", long.class);
            FIELD_38 = lookup.findVarHandle(BigDataClass.class, "i38", long.class);
            FIELD_39 = lookup.findVarHandle(BigDataClass.class, "i39", long.class);
            FIELD_40 = lookup.findVarHandle(BigDataClass.class, "i40", long.class);
            FIELD_41 = lookup.findVarHandle(BigDataClass.class, "i41", long.class);
            FIELD_42 = lookup.findVarHandle(BigDataClass.class, "i42", long.class);
            FIELD_43 = lookup.findVarHandle(BigDataClass.class, "i43", long.class);
            FIELD_44 = lookup.findVarHandle(BigDataClass.class, "i44", long.class);
            FIELD_45 = lookup.findVarHandle(BigDataClass.class, "i45", long.class);
            FIELD_46 = lookup.findVarHandle(BigDataClass.class, "i46", long.class);
            FIELD_47 = lookup.findVarHandle(BigDataClass.class, "i47", long.class);
            FIELD_48 = lookup.findVarHandle(BigDataClass.class, "i48", long.class);
            FIELD_49 = lookup.findVarHandle(BigDataClass.class, "i49", long.class);
            FIELD_50 = lookup.findVarHandle(BigDataClass.class, "i50", long.class);
            FIELD_51 = lookup.findVarHandle(BigDataClass.class, "i51", long.class);
            FIELD_52 = lookup.findVarHandle(BigDataClass.class, "i52", long.class);
            FIELD_53 = lookup.findVarHandle(BigDataClass.class, "i53", long.class);
            FIELD_54 = lookup.findVarHandle(BigDataClass.class, "i54", long.class);
            FIELD_55 = lookup.findVarHandle(BigDataClass.class, "i55", long.class);
            FIELD_56 = lookup.findVarHandle(BigDataClass.class, "i56", long.class);
            FIELD_57 = lookup.findVarHandle(BigDataClass.class, "i57", long.class);
            FIELD_58 = lookup.findVarHandle(BigDataClass.class, "i58", long.class);
            FIELD_59 = lookup.findVarHandle(BigDataClass.class, "i59", long.class);
            FIELD_60 = lookup.findVarHandle(BigDataClass.class, "i60", long.class);
            FIELD_61 = lookup.findVarHandle(BigDataClass.class, "i61", long.class);
            FIELD_62 = lookup.findVarHandle(BigDataClass.class, "i62", long.class);
            FIELD_63 = lookup.findVarHandle(BigDataClass.class, "i63", long.class);
            FIELD_64 = lookup.findVarHandle(BigDataClass.class, "i64", long.class);
            FIELD_65 = lookup.findVarHandle(BigDataClass.class, "i65", long.class);
            FIELD_66 = lookup.findVarHandle(BigDataClass.class, "i66", long.class);
            FIELD_67 = lookup.findVarHandle(BigDataClass.class, "i67", long.class);
            FIELD_68 = lookup.findVarHandle(BigDataClass.class, "i68", long.class);
            FIELD_69 = lookup.findVarHandle(BigDataClass.class, "i69", long.class);
            FIELD_70 = lookup.findVarHandle(BigDataClass.class, "i70", long.class);
            FIELD_71 = lookup.findVarHandle(BigDataClass.class, "i71", long.class);
            FIELD_72 = lookup.findVarHandle(BigDataClass.class, "i72", long.class);
            FIELD_73 = lookup.findVarHandle(BigDataClass.class, "i73", long.class);
            FIELD_74 = lookup.findVarHandle(BigDataClass.class, "i74", long.class);
            FIELD_75 = lookup.findVarHandle(BigDataClass.class, "i75", long.class);
            FIELD_76 = lookup.findVarHandle(BigDataClass.class, "i76", long.class);
            FIELD_77 = lookup.findVarHandle(BigDataClass.class, "i77", long.class);
            FIELD_78 = lookup.findVarHandle(BigDataClass.class, "i78", long.class);
            FIELD_79 = lookup.findVarHandle(BigDataClass.class, "i79", long.class);
            FIELD_80 = lookup.findVarHandle(BigDataClass.class, "i80", long.class);
            FIELD_81 = lookup.findVarHandle(BigDataClass.class, "i81", long.class);
            FIELD_82 = lookup.findVarHandle(BigDataClass.class, "i82", long.class);
            FIELD_83 = lookup.findVarHandle(BigDataClass.class, "i83", long.class);
            FIELD_84 = lookup.findVarHandle(BigDataClass.class, "i84", long.class);
            FIELD_85 = lookup.findVarHandle(BigDataClass.class, "i85", long.class);
            FIELD_86 = lookup.findVarHandle(BigDataClass.class, "i86", long.class);
            FIELD_87 = lookup.findVarHandle(BigDataClass.class, "i87", long.class);
            FIELD_88 = lookup.findVarHandle(BigDataClass.class, "i88", long.class);
            FIELD_89 = lookup.findVarHandle(BigDataClass.class, "i89", long.class);
            FIELD_90 = lookup.findVarHandle(BigDataClass.class, "i90", long.class);
            FIELD_91 = lookup.findVarHandle(BigDataClass.class, "i91", long.class);
            FIELD_92 = lookup.findVarHandle(BigDataClass.class, "i92", long.class);
            FIELD_93 = lookup.findVarHandle(BigDataClass.class, "i93", long.class);
            FIELD_94 = lookup.findVarHandle(BigDataClass.class, "i94", long.class);
            FIELD_95 = lookup.findVarHandle(BigDataClass.class, "i95", long.class);
            FIELD_96 = lookup.findVarHandle(BigDataClass.class, "i96", long.class);
            FIELD_97 = lookup.findVarHandle(BigDataClass.class, "i97", long.class);
            FIELD_98 = lookup.findVarHandle(BigDataClass.class, "i98", long.class);
            FIELD_99 = lookup.findVarHandle(BigDataClass.class, "i99", long.class);
            FIELD_100 = lookup.findVarHandle(BigDataClass.class, "i100", long.class);
            FIELD_101 = lookup.findVarHandle(BigDataClass.class, "i101", long.class);
            FIELD_102 = lookup.findVarHandle(BigDataClass.class, "i102", long.class);
            FIELD_103 = lookup.findVarHandle(BigDataClass.class, "i103", long.class);
            FIELD_104 = lookup.findVarHandle(BigDataClass.class, "i104", long.class);
            FIELD_105 = lookup.findVarHandle(BigDataClass.class, "i105", long.class);
            FIELD_106 = lookup.findVarHandle(BigDataClass.class, "i106", long.class);
            FIELD_107 = lookup.findVarHandle(BigDataClass.class, "i107", long.class);
            FIELD_108 = lookup.findVarHandle(BigDataClass.class, "i108", long.class);
            FIELD_109 = lookup.findVarHandle(BigDataClass.class, "i109", long.class);
            FIELD_110 = lookup.findVarHandle(BigDataClass.class, "i110", long.class);
            FIELD_111 = lookup.findVarHandle(BigDataClass.class, "i111", long.class);
            FIELD_112 = lookup.findVarHandle(BigDataClass.class, "i112", long.class);
            FIELD_113 = lookup.findVarHandle(BigDataClass.class, "i113", long.class);
            FIELD_114 = lookup.findVarHandle(BigDataClass.class, "i114", long.class);
            FIELD_115 = lookup.findVarHandle(BigDataClass.class, "i115", long.class);
            FIELD_116 = lookup.findVarHandle(BigDataClass.class, "i116", long.class);
            FIELD_117 = lookup.findVarHandle(BigDataClass.class, "i117", long.class);
            FIELD_118 = lookup.findVarHandle(BigDataClass.class, "i118", long.class);
            FIELD_119 = lookup.findVarHandle(BigDataClass.class, "i119", long.class);
            FIELD_120 = lookup.findVarHandle(BigDataClass.class, "i120", long.class);
            FIELD_121 = lookup.findVarHandle(BigDataClass.class, "i121", long.class);
            FIELD_122 = lookup.findVarHandle(BigDataClass.class, "i122", long.class);
            FIELD_123 = lookup.findVarHandle(BigDataClass.class, "i123", long.class);
            FIELD_124 = lookup.findVarHandle(BigDataClass.class, "i124", long.class);
            FIELD_125 = lookup.findVarHandle(BigDataClass.class, "i125", long.class);
            FIELD_126 = lookup.findVarHandle(BigDataClass.class, "i126", long.class);
            CONSTRUCTOR = lookup.findConstructor(BigDataClass.class, MethodType.methodType(void.class));
        } catch (NoSuchMethodException | IllegalAccessException | NoSuchFieldException e) {
            throw new RuntimeException(e);
        }
    }
}
